PckgrBot/winget-pkgs-private

manifests/e/Easeware/DriverEasy/5.8.1/Easeware.DriverEasy.installer.yaml, manifests/e/Easeware/DriverEasy/5.8.1/Easeware.DriverEasy.locale.de-DE.yaml, manifests/e/Easeware/DriverEasy/5.8.1/Easeware.DriverEasy.locale.en-US.yaml, manifests/e/Easeware/DriverEasy/5.8.1/Easeware.DriverEasy.yaml
=> Easeware.DriverEasy version 5.8.1

manifests/m/Microsoft/AzureDataStudio/1.47.1/Microsoft.AzureDataStudio.installer.yaml, manifests/m/Microsoft/AzureDataStudio/1.47.1/Microsoft.AzureDataStudio.locale.en-US.yaml, manifests/m/Microsoft/AzureDataStudio/1.47.1/Microsoft.AzureDataStudio.yaml
=> New version: Microsoft.AzureDataStudio version 1.47.1

manifests/s/SlackTechnologies/Slack/4.36.140/SlackTechnologies.Slack.installer.yaml, manifests/s/SlackTechnologies/Slack/4.36.140/SlackTechnologies.Slack.locale.en-US.yaml, manifests/s/SlackTechnologies/Slack/4.36.140/SlackTechnologies.Slack.yaml
=> New version: SlackTechnologies.Slack version 4.36.140

manifests/p/Puppet/puppet-agent/8.4.0/Puppet.puppet-agent.installer.yaml, manifests/p/Puppet/puppet-agent/8.4.0/Puppet.puppet-agent.locale.en-US.yaml, manifests/p/Puppet/puppet-agent/8.4.0/Puppet.puppet-agent.yaml
=> New version: Puppet.puppet-agent version 8.4.0

manifests/g/Google/GoogleDrive/85.0.37.0/Google.GoogleDrive.installer.yaml, manifests/g/Google/GoogleDrive/85.0.37.0/Google.GoogleDrive.locale.en-US.yaml, manifests/g/Google/GoogleDrive/85.0.37.0/Google.GoogleDrive.locale.zh-CN.yaml, manifests/g/Google/GoogleDrive/85.0.37.0/Google.GoogleDrive.yaml
=> New version: Google.GoogleDrive version 85.0.37.0

manifests/w/WinMerge/WinMerge/2.16.38/WinMerge.WinMerge.installer.yaml, manifests/w/WinMerge/WinMerge/2.16.38/WinMerge.WinMerge.locale.en-US.yaml, manifests/w/WinMerge/WinMerge/2.16.38/WinMerge.WinMerge.yaml
=> New version: WinMerge.WinMerge version 2.16.38

manifests/8/8x8/Work/8.9.3/8x8.Work.installer.yaml, manifests/8/8x8/Work/8.9.3/8x8.Work.locale.en-US.yaml, manifests/8/8x8/Work/8.9.3/8x8.Work.yaml
=> 8x8.Work version 8.9.3

manifests/a/Airtame/Airtame/4.8.0/Airtame.Airtame.installer.yaml, manifests/a/Airtame/Airtame/4.8.0/Airtame.Airtame.locale.en-US.yaml, manifests/a/Airtame/Airtame/4.8.0/Airtame.Airtame.yaml
=> New version: Airtame.Airtame version 4.8.0

manifests/m/Microsoft/PowerAutomateDesktop/2.39.306.23341/Microsoft.PowerAutomateDesktop.installer.yaml, manifests/m/Microsoft/PowerAutomateDesktop/2.39.306.23341/Microsoft.PowerAutomateDesktop.locale.en-US.yaml, manifests/m/Microsoft/PowerAutomateDesktop/2.39.306.23341/Microsoft.PowerAutomateDesktop.yaml
=> Microsoft.PowerAutomateDesktop version 2.39.306.23341

manifests/m/Microsoft/PowerAutomateDesktop/2.40.157.24023/Microsoft.PowerAutomateDesktop.installer.yaml, manifests/m/Microsoft/PowerAutomateDesktop/2.40.157.24023/Microsoft.PowerAutomateDesktop.locale.en-US.yaml, manifests/m/Microsoft/PowerAutomateDesktop/2.40.157.24023/Microsoft.PowerAutomateDesktop.yaml
=> New version: Microsoft.PowerAutomateDesktop version 2.40.157.24023

manifests/g/Google/Chrome/120.0.6099.276/Google.Chrome.installer.yaml, manifests/g/Google/Chrome/120.0.6099.276/Google.Chrome.locale.en-US.yaml, manifests/g/Google/Chrome/120.0.6099.276/Google.Chrome.locale.nb-NO.yaml, manifests/g/Google/Chrome/120.0.6099.276/Google.Chrome.locale.zh-CN.yaml, manifests/g/Google/Chrome/120.0.6099.276/Google.Chrome.yaml
=> New version: Google.Chrome version 120.0.6099.276

manifests/j/Jabra/Direct/6.13.01801/Jabra.Direct.installer.yaml, manifests/j/Jabra/Direct/6.13.01801/Jabra.Direct.locale.en-US.yaml, manifests/j/Jabra/Direct/6.13.01801/Jabra.Direct.yaml
=> New version: Jabra.Direct version 6.13.01801

manifests/a/Anydo/Anydo/5.0.57.1/Anydo.Anydo.installer.yaml, manifests/a/Anydo/Anydo/5.0.57.1/Anydo.Anydo.locale.en-US.yaml, manifests/a/Anydo/Anydo/5.0.57.1/Anydo.Anydo.yaml
=> New version: Anydo.Anydo version 5.0.57.1

manifests/n/Nextcloud/NextcloudDesktop/3.11.1/Nextcloud.NextcloudDesktop.installer.yaml, manifests/n/Nextcloud/NextcloudDesktop/3.11.1/Nextcloud.NextcloudDesktop.locale.en-US.yaml, manifests/n/Nextcloud/NextcloudDesktop/3.11.1/Nextcloud.NextcloudDesktop.yaml
=> New version: Nextcloud.NextcloudDesktop version 3.11.1

manifests/m/Microsoft/PowerBI/2.124.2028.0/Microsoft.PowerBI.installer.yaml, manifests/m/Microsoft/PowerBI/2.124.2028.0/Microsoft.PowerBI.locale.en-US.yaml, manifests/m/Microsoft/PowerBI/2.124.2028.0/Microsoft.PowerBI.yaml
=> New version: Microsoft.PowerBI version 2.124.2028.0

manifests/e/evernote/evernote/10.74.1/evernote.evernote.installer.yaml, manifests/e/evernote/evernote/10.74.1/evernote.evernote.locale.en-US.yaml, manifests/e/evernote/evernote/10.74.1/evernote.evernote.yaml
=> New version: evernote.evernote version 10.74.1

manifests/m/Microsoft/VisualStudio/2022/Professional/17.8.5/Microsoft.VisualStudio.2022.Professional.installer.yaml, manifests/m/Microsoft/VisualStudio/2022/Professional/17.8.5/Microsoft.VisualStudio.2022.Professional.locale.en-US.yaml, manifests/m/Microsoft/VisualStudio/2022/Professional/17.8.5/Microsoft.VisualStudio.2022.Professional.yaml
=> Microsoft.VisualStudio.2022.Professional version 17.8.5

manifests/m/Microsoft/VisualStudio/2022/Community/17.8.6/Microsoft.VisualStudio.2022.Community.installer.yaml, manifests/m/Microsoft/VisualStudio/2022/Community/17.8.6/Microsoft.VisualStudio.2022.Community.locale.en-US.yaml, manifests/m/Microsoft/VisualStudio/2022/Community/17.8.6/Microsoft.VisualStudio.2022.Community.yaml
=> Microsoft.VisualStudio.2022.Community version 17.8.6

manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.installer.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.en-US.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.fr-FR.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.it-IT.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.ja-JP.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.ko-KR.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.pt-BR.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.ru-RU.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.zh-CN.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.locale.zh-TW.yaml, manifests/m/Microsoft/WindowsTerminal/1.18.3181.0/Microsoft.WindowsTerminal.yaml
=> Microsoft.WindowsTerminal version 1.18.3181.0

manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.8.6/Microsoft.VisualStudio.2022.Enterprise.installer.yaml, manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.8.6/Microsoft.VisualStudio.2022.Enterprise.locale.en-US.yaml, manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.8.6/Microsoft.VisualStudio.2022.Enterprise.yaml
=> Microsoft.VisualStudio.2022.Enterprise version 17.8.6

manifests/z/Zoom/Zoom/5.17.5.31030/Zoom.Zoom.installer.yaml, manifests/z/Zoom/Zoom/5.17.5.31030/Zoom.Zoom.locale.en-US.yaml, manifests/z/Zoom/Zoom/5.17.5.31030/Zoom.Zoom.locale.zh-CN.yaml, manifests/z/Zoom/Zoom/5.17.5.31030/Zoom.Zoom.yaml
=> Zoom.Zoom version 5.17.5.31030

manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.installer.yaml, manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.locale.en-US.yaml, manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.locale.zh-CN.yaml, manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.yaml
=> New version: Zoom.Zoom version 5.17.7.31859

manifests/g/GitHub/cli/2.43.0/GitHub.cli.installer.yaml, manifests/g/GitHub/cli/2.43.0/GitHub.cli.locale.en-US.yaml, manifests/g/GitHub/cli/2.43.0/GitHub.cli.yaml
=> New version: GitHub.cli version 2.43.0

manifests/o/Opera/Opera/106.0.4998.70/Opera.Opera.installer.yaml, manifests/o/Opera/Opera/106.0.4998.70/Opera.Opera.locale.en-US.yaml, manifests/o/Opera/Opera/106.0.4998.70/Opera.Opera.locale.nb-NO.yaml, manifests/o/Opera/Opera/106.0.4998.70/Opera.Opera.yaml
=> New version: Opera.Opera version 106.0.4998.70

manifests/a/Amazon/AWSCLI/2.15.16/Amazon.AWSCLI.installer.yaml, manifests/a/Amazon/AWSCLI/2.15.16/Amazon.AWSCLI.locale.en-US.yaml, manifests/a/Amazon/AWSCLI/2.15.16/Amazon.AWSCLI.yaml
=> New version: Amazon.AWSCLI version 2.15.16

manifests/o/OpenWhisperSystems/Signal/6.46.0/OpenWhisperSystems.Signal.installer.yaml, manifests/o/OpenWhisperSystems/Signal/6.46.0/OpenWhisperSystems.Signal.locale.en-US.yaml, manifests/o/OpenWhisperSystems/Signal/6.46.0/OpenWhisperSystems.Signal.yaml
=> New version: OpenWhisperSystems.Signal version 6.46.0

manifests/e/Egnyte/EgnyteDesktopApp/3.16.0.138/Egnyte.EgnyteDesktopApp.installer.yaml, manifests/e/Egnyte/EgnyteDesktopApp/3.16.0.138/Egnyte.EgnyteDesktopApp.locale.en-US.yaml, manifests/e/Egnyte/EgnyteDesktopApp/3.16.0.138/Egnyte.EgnyteDesktopApp.yaml
=> New version: Egnyte.EgnyteDesktopApp version 3.16.0.138

manifests/g/Grammarly/Grammarly/1.2.62.1299/Grammarly.Grammarly.installer.yaml, manifests/g/Grammarly/Grammarly/1.2.62.1299/Grammarly.Grammarly.locale.en-US.yaml, manifests/g/Grammarly/Grammarly/1.2.62.1299/Grammarly.Grammarly.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly/1.2.62.1299/Grammarly.Grammarly.yaml
=> New version: Grammarly.Grammarly version 1.2.62.1299

manifests/d/DuongDieuPhap/ImageGlass/9.0.10.201/DuongDieuPhap.ImageGlass.installer.yaml, manifests/d/DuongDieuPhap/ImageGlass/9.0.10.201/DuongDieuPhap.ImageGlass.locale.en-US.yaml, manifests/d/DuongDieuPhap/ImageGlass/9.0.10.201/DuongDieuPhap.ImageGlass.yaml
=> New version: DuongDieuPhap.ImageGlass version 9.0.10.201

manifests/d/Discord/Discord/1.0.9032/Discord.Discord.installer.yaml, manifests/d/Discord/Discord/1.0.9032/Discord.Discord.locale.en-US.yaml, manifests/d/Discord/Discord/1.0.9032/Discord.Discord.locale.pt-BR.yaml, manifests/d/Discord/Discord/1.0.9032/Discord.Discord.locale.zh-CN.yaml, manifests/d/Discord/Discord/1.0.9032/Discord.Discord.yaml
=> New version: Discord.Discord version 1.0.9032

manifests/g/GitHub/cli/2.43.1/GitHub.cli.installer.yaml, manifests/g/GitHub/cli/2.43.1/GitHub.cli.locale.en-US.yaml, manifests/g/GitHub/cli/2.43.1/GitHub.cli.yaml
=> New version: GitHub.cli version 2.43.1

manifests/b/Brave/Brave/121.1.62.153/Brave.Brave.installer.yaml, manifests/b/Brave/Brave/121.1.62.153/Brave.Brave.locale.en-US.yaml, manifests/b/Brave/Brave/121.1.62.153/Brave.Brave.locale.zh-CN.yaml, manifests/b/Brave/Brave/121.1.62.153/Brave.Brave.yaml
=> Brave.Brave version 121.1.62.153

manifests/m/Microsoft/Teams/Classic/1.7.00.1864/Microsoft.Teams.Classic.installer.yaml, manifests/m/Microsoft/Teams/Classic/1.7.00.1864/Microsoft.Teams.Classic.locale.en-US.yaml, manifests/m/Microsoft/Teams/Classic/1.7.00.1864/Microsoft.Teams.Classic.yaml
=> New version: Microsoft.Teams.Classic version 1.7.00.1864

manifests/d/Docker/DockerDesktop/4.27.1/Docker.DockerDesktop.installer.yaml, manifests/d/Docker/DockerDesktop/4.27.1/Docker.DockerDesktop.locale.en-US.yaml, manifests/d/Docker/DockerDesktop/4.27.1/Docker.DockerDesktop.yaml
=> New version: Docker.DockerDesktop version 4.27.1

manifests/m/Microsoft/VisualStudioCode/1.85.2/Microsoft.VisualStudioCode.installer.yaml, manifests/m/Microsoft/VisualStudioCode/1.85.2/Microsoft.VisualStudioCode.locale.en-US.yaml, manifests/m/Microsoft/VisualStudioCode/1.85.2/Microsoft.VisualStudioCode.yaml
=> Microsoft.VisualStudioCode version 1.85.2

manifests/m/Microsoft/PowerToys/0.77.0/Microsoft.PowerToys.installer.yaml, manifests/m/Microsoft/PowerToys/0.77.0/Microsoft.PowerToys.locale.en-US.yaml, manifests/m/Microsoft/PowerToys/0.77.0/Microsoft.PowerToys.yaml
=> Microsoft.PowerToys version 0.77.0

manifests/g/geeksoftwareGmbH/PDF24Creator/11.16.0/geeksoftwareGmbH.PDF24Creator.installer.yaml, manifests/g/geeksoftwareGmbH/PDF24Creator/11.16.0/geeksoftwareGmbH.PDF24Creator.locale.de-DE.yaml, manifests/g/geeksoftwareGmbH/PDF24Creator/11.16.0/geeksoftwareGmbH.PDF24Creator.locale.en-US.yaml, manifests/g/geeksoftwareGmbH/PDF24Creator/11.16.0/geeksoftwareGmbH.PDF24Creator.yaml
=> New version: geeksoftwareGmbH.PDF24Creator version 11.16.0

manifests/l/Logitech/Options/10.20.11/Logitech.Options.installer.yaml, manifests/l/Logitech/Options/10.20.11/Logitech.Options.locale.en-US.yaml, manifests/l/Logitech/Options/10.20.11/Logitech.Options.locale.ja-JP.yaml, manifests/l/Logitech/Options/10.20.11/Logitech.Options.yaml
=> New version: Logitech.Options version 10.20.11

manifests/g/Google/Chrome/121.0.6167.140/Google.Chrome.installer.yaml, manifests/g/Google/Chrome/121.0.6167.140/Google.Chrome.locale.en-US.yaml, manifests/g/Google/Chrome/121.0.6167.140/Google.Chrome.locale.nb-NO.yaml, manifests/g/Google/Chrome/121.0.6167.140/Google.Chrome.locale.zh-CN.yaml, manifests/g/Google/Chrome/121.0.6167.140/Google.Chrome.yaml
=> New version: Google.Chrome version 121.0.6167.140

manifests/s/SonicWALL/NetExtender/10.2.339/SonicWALL.NetExtender.installer.yaml, manifests/s/SonicWALL/NetExtender/10.2.339/SonicWALL.NetExtender.locale.en-US.yaml, manifests/s/SonicWALL/NetExtender/10.2.339/SonicWALL.NetExtender.yaml
=> New version: SonicWALL.NetExtender version 10.2.339

manifests/a/AntibodySoftware/WizTree_Pckgr/4.18/AntibodySoftware.WizTree_Pckgr.installer.yaml, manifests/a/AntibodySoftware/WizTree_Pckgr/4.18/AntibodySoftware.WizTree_Pckgr.locale.en-US.yaml, manifests/a/AntibodySoftware/WizTree_Pckgr/4.18/AntibodySoftware.WizTree_Pckgr.yaml
=> New version: AntibodySoftware.WizTree_Pckgr version 4.18

manifests/a/Amazon/AWSCLI_Pckgr/2.15.17/Amazon.AWSCLI_Pckgr.installer.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.17/Amazon.AWSCLI_Pckgr.locale.en-US.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.17/Amazon.AWSCLI_Pckgr.yaml
=> New version: Amazon.AWSCLI_Pckgr version 2.15.17

manifests/c/Citrix/Workspace_Pckgr/23.11.1.140/Citrix.Workspace_Pckgr.installer.yaml, manifests/c/Citrix/Workspace_Pckgr/23.11.1.140/Citrix.Workspace_Pckgr.locale.en-US.yaml, manifests/c/Citrix/Workspace_Pckgr/23.11.1.140/Citrix.Workspace_Pckgr.yaml
=> New version: Citrix.Workspace_Pckgr version 23.11.1.140

manifests/g/Grammarly/Grammarly_Pckgr/1.2.62.1306/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.62.1306/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.62.1306/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.62.1306/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.62.1306

manifests/d/dbeaver/dbeaver_Pckgr/23.3.4/dbeaver.dbeaver_Pckgr.installer.yaml, manifests/d/dbeaver/dbeaver_Pckgr/23.3.4/dbeaver.dbeaver_Pckgr.locale.en-US.yaml, manifests/d/dbeaver/dbeaver_Pckgr/23.3.4/dbeaver.dbeaver_Pckgr.yaml
=> New version: dbeaver.dbeaver_Pckgr version 23.3.4

manifests/c/Canva/Canva_Pckgr/1.81.0/Canva.Canva_Pckgr.installer.yaml, manifests/c/Canva/Canva_Pckgr/1.81.0/Canva.Canva_Pckgr.locale.en-US.yaml, manifests/c/Canva/Canva_Pckgr/1.81.0/Canva.Canva_Pckgr.yaml
=> New version: Canva.Canva_Pckgr version 1.81.0

manifests/k/Krisp/Krisp_Pckgr/2.33.3/Krisp.Krisp_Pckgr.installer.yaml, manifests/k/Krisp/Krisp_Pckgr/2.33.3/Krisp.Krisp_Pckgr.locale.en-US.yaml, manifests/k/Krisp/Krisp_Pckgr/2.33.3/Krisp.Krisp_Pckgr.yaml
=> New version: Krisp.Krisp_Pckgr version 2.33.3

manifests/k/Kitware/CMake_Pckgr/3.28.3/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.28.3/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.28.3/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.28.3

manifests/s/Surfshark/Surfshark_Pckgr/5.5.2999/Surfshark.Surfshark_Pckgr.installer.yaml, manifests/s/Surfshark/Surfshark_Pckgr/5.5.2999/Surfshark.Surfshark_Pckgr.locale.en-US.yaml, manifests/s/Surfshark/Surfshark_Pckgr/5.5.2999/Surfshark.Surfshark_Pckgr.yaml
=> New version: Surfshark.Surfshark_Pckgr version 5.5.2999

manifests/g/Google/GoogleDrive_Pckgr/86.0.2.0/Google.GoogleDrive_Pckgr.installer.yaml, manifests/g/Google/GoogleDrive_Pckgr/86.0.2.0/Google.GoogleDrive_Pckgr.locale.en-US.yaml, manifests/g/Google/GoogleDrive_Pckgr/86.0.2.0/Google.GoogleDrive_Pckgr.locale.zh-CN.yaml, manifests/g/Google/GoogleDrive_Pckgr/86.0.2.0/Google.GoogleDrive_Pckgr.yaml
=> New version: Google.GoogleDrive_Pckgr version 86.0.2.0

manifests/m/Microsoft/Edge_Pckgr/121.0.2277.106/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.106/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.106/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.106/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 121.0.2277.106

manifests/a/Amazon/WorkspacesClient_Pckgr/5.18.0/Amazon.WorkspacesClient_Pckgr.installer.yaml, manifests/a/Amazon/WorkspacesClient_Pckgr/5.18.0/Amazon.WorkspacesClient_Pckgr.locale.en-US.yaml, manifests/a/Amazon/WorkspacesClient_Pckgr/5.18.0/Amazon.WorkspacesClient_Pckgr.yaml
=> New version: Amazon.WorkspacesClient_Pckgr version 5.18.0

manifests/7/7zip/7zip_Pckgr/23.01/7zip.7zip_Pckgr.installer.yaml, manifests/7/7zip/7zip_Pckgr/23.01/7zip.7zip_Pckgr.locale.en-US.yaml, manifests/7/7zip/7zip_Pckgr/23.01/7zip.7zip_Pckgr.locale.zh-CN.yaml, manifests/7/7zip/7zip_Pckgr/23.01/7zip.7zip_Pckgr.yaml
=> 7zip.7zip_Pckgr version 23.01

manifests/n/Notepad++/Notepad++_Pckgr/8.6.2/Notepad++.Notepad++_Pckgr.installer.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.2/Notepad++.Notepad++_Pckgr.locale.en-US.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.2/Notepad++.Notepad++_Pckgr.yaml
=> Notepad++.Notepad++_Pckgr version 8.6.2

manifests/m/Microsoft/PowerToys_Pckgr/0.78.0/Microsoft.PowerToys_Pckgr.installer.yaml, manifests/m/Microsoft/PowerToys_Pckgr/0.78.0/Microsoft.PowerToys_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/PowerToys_Pckgr/0.78.0/Microsoft.PowerToys_Pckgr.yaml
=> New version: Microsoft.PowerToys_Pckgr version 0.78.0

manifests/c/Cisco/Webex_Pckgr/3.19.0.28454/Cisco.Webex_Pckgr.installer.yaml, manifests/c/Cisco/Webex_Pckgr/3.19.0.28454/Cisco.Webex_Pckgr.locale.en-US.yaml, manifests/c/Cisco/Webex_Pckgr/3.19.0.28454/Cisco.Webex_Pckgr.yaml
=> Cisco.Webex_Pckgr version 3.19.0.28454

manifests/g/Google/Chrome_Pckgr/121.0.6167.160/Google.Chrome_Pckgr.installer.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.160/Google.Chrome_Pckgr.locale.en-US.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.160/Google.Chrome_Pckgr.locale.nb-NO.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.160/Google.Chrome_Pckgr.locale.zh-CN.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.160/Google.Chrome_Pckgr.yaml
=> New version: Google.Chrome_Pckgr version 121.0.6167.160

manifests/o/Opera/OperaGX_Pckgr/106.0.4998.74/Opera.OperaGX_Pckgr.installer.yaml, manifests/o/Opera/OperaGX_Pckgr/106.0.4998.74/Opera.OperaGX_Pckgr.locale.en-US.yaml, manifests/o/Opera/OperaGX_Pckgr/106.0.4998.74/Opera.OperaGX_Pckgr.yaml
=> New version: Opera.OperaGX_Pckgr version 106.0.4998.74

manifests/g/Grammarly/Grammarly_Pckgr/1.2.63.1310/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.63.1310/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.63.1310/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.63.1310/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.63.1310

manifests/o/Opera/OperaGX_Pckgr/106.0.4998.76/Opera.OperaGX_Pckgr.installer.yaml, manifests/o/Opera/OperaGX_Pckgr/106.0.4998.76/Opera.OperaGX_Pckgr.locale.en-US.yaml, manifests/o/Opera/OperaGX_Pckgr/106.0.4998.76/Opera.OperaGX_Pckgr.yaml
=> New version: Opera.OperaGX_Pckgr version 106.0.4998.76

manifests/e/evernote/evernote_Pckgr/10.75.1/evernote.evernote_Pckgr.installer.yaml, manifests/e/evernote/evernote_Pckgr/10.75.1/evernote.evernote_Pckgr.locale.en-US.yaml, manifests/e/evernote/evernote_Pckgr/10.75.1/evernote.evernote_Pckgr.yaml
=> New version: evernote.evernote_Pckgr version 10.75.1

manifests/w/WiseCleaner/WiseDiskCleaner_Pckgr/11.0.8/WiseCleaner.WiseDiskCleaner_Pckgr.installer.yaml, manifests/w/WiseCleaner/WiseDiskCleaner_Pckgr/11.0.8/WiseCleaner.WiseDiskCleaner_Pckgr.locale.en-US.yaml, manifests/w/WiseCleaner/WiseDiskCleaner_Pckgr/11.0.8/WiseCleaner.WiseDiskCleaner_Pckgr.yaml
=> New version: WiseCleaner.WiseDiskCleaner_Pckgr version 11.0.8

manifests/o/Opera/Opera_Pckgr/107.0.5045.15/Opera.Opera_Pckgr.installer.yaml, manifests/o/Opera/Opera_Pckgr/107.0.5045.15/Opera.Opera_Pckgr.locale.en-US.yaml, manifests/o/Opera/Opera_Pckgr/107.0.5045.15/Opera.Opera_Pckgr.locale.nb-NO.yaml, manifests/o/Opera/Opera_Pckgr/107.0.5045.15/Opera.Opera_Pckgr.yaml
=> New version: Opera.Opera_Pckgr version 107.0.5045.15

manifests/d/Dialpad/Dialpad_Pckgr/2401.4.0/Dialpad.Dialpad_Pckgr.installer.yaml, manifests/d/Dialpad/Dialpad_Pckgr/2401.4.0/Dialpad.Dialpad_Pckgr.locale.en-US.yaml, manifests/d/Dialpad/Dialpad_Pckgr/2401.4.0/Dialpad.Dialpad_Pckgr.yaml
=> New version: Dialpad.Dialpad_Pckgr version 2401.4.0

manifests/a/Amazon/AWSCLI_Pckgr/2.15.18/Amazon.AWSCLI_Pckgr.installer.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.18/Amazon.AWSCLI_Pckgr.locale.en-US.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.18/Amazon.AWSCLI_Pckgr.yaml
=> New version: Amazon.AWSCLI_Pckgr version 2.15.18

manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.0/Bitwarden.Bitwarden_Pckgr.installer.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.0/Bitwarden.Bitwarden_Pckgr.locale.en-US.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.0/Bitwarden.Bitwarden_Pckgr.locale.pt-BR.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.0/Bitwarden.Bitwarden_Pckgr.locale.zh-CN.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.0/Bitwarden.Bitwarden_Pckgr.yaml
=> New version: Bitwarden.Bitwarden_Pckgr version 2024.2.0

manifests/o/OpenWhisperSystems/Signal_Pckgr/6.47.0/OpenWhisperSystems.Signal_Pckgr.installer.yaml, manifests/o/OpenWhisperSystems/Signal_Pckgr/6.47.0/OpenWhisperSystems.Signal_Pckgr.locale.en-US.yaml, manifests/o/OpenWhisperSystems/Signal_Pckgr/6.47.0/OpenWhisperSystems.Signal_Pckgr.yaml
=> New version: OpenWhisperSystems.Signal_Pckgr version 6.47.0

manifests/m/Microsoft/Edge_Pckgr/121.0.2277.110/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.110/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.110/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.110/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 121.0.2277.110

manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.0/Microsoft.VisualStudioCode_Pckgr.installer.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.0/Microsoft.VisualStudioCode_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.0/Microsoft.VisualStudioCode_Pckgr.yaml
=> New version: Microsoft.VisualStudioCode_Pckgr version 1.86.0

manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.16.1.139/Egnyte.EgnyteDesktopApp_Pckgr.installer.yaml, manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.16.1.139/Egnyte.EgnyteDesktopApp_Pckgr.locale.en-US.yaml, manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.16.1.139/Egnyte.EgnyteDesktopApp_Pckgr.yaml
=> New version: Egnyte.EgnyteDesktopApp_Pckgr version 3.16.1.139

manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.1/Microsoft.VisualStudioCode_Pckgr.installer.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.1/Microsoft.VisualStudioCode_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.1/Microsoft.VisualStudioCode_Pckgr.yaml
=> New version: Microsoft.VisualStudioCode_Pckgr version 1.86.1

manifests/d/Docker/DockerDesktop_Pckgr/4.27.2/Docker.DockerDesktop_Pckgr.installer.yaml, manifests/d/Docker/DockerDesktop_Pckgr/4.27.2/Docker.DockerDesktop_Pckgr.locale.en-US.yaml, manifests/d/Docker/DockerDesktop_Pckgr/4.27.2/Docker.DockerDesktop_Pckgr.yaml
=> New version: Docker.DockerDesktop_Pckgr version 4.27.2

manifests/d/Dropbox/Dropbox_Pckgr/192.4.4605/Dropbox.Dropbox_Pckgr.installer.yaml, manifests/d/Dropbox/Dropbox_Pckgr/192.4.4605/Dropbox.Dropbox_Pckgr.locale.en-US.yaml, manifests/d/Dropbox/Dropbox_Pckgr/192.4.4605/Dropbox.Dropbox_Pckgr.yaml
=> New version: Dropbox.Dropbox_Pckgr version 192.4.4605

manifests/g/Google/Chrome_Pckgr/121.0.6167.161/Google.Chrome_Pckgr.installer.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.161/Google.Chrome_Pckgr.locale.en-US.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.161/Google.Chrome_Pckgr.locale.nb-NO.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.161/Google.Chrome_Pckgr.locale.zh-CN.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.161/Google.Chrome_Pckgr.yaml
=> New version: Google.Chrome_Pckgr version 121.0.6167.161

manifests/m/Microsoft/Edge_Pckgr/121.0.2277.112/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.112/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.112/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.112/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 121.0.2277.112

manifests/m/Microsoft/DotNet/Runtime/6_Pckgr/6.0.26/Microsoft.DotNet.Runtime.6_Pckgr.installer.yaml, manifests/m/Microsoft/DotNet/Runtime/6_Pckgr/6.0.26/Microsoft.DotNet.Runtime.6_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/DotNet/Runtime/6_Pckgr/6.0.26/Microsoft.DotNet.Runtime.6_Pckgr.yaml
=> Microsoft.DotNet.Runtime.6_Pckgr version 6.0.26

manifests/m/Microsoft/VCRedist/2015+/x86_Pckgr/14.38.33130.0/Microsoft.VCRedist.2015+.x86_Pckgr.installer.yaml, manifests/m/Microsoft/VCRedist/2015+/x86_Pckgr/14.38.33130.0/Microsoft.VCRedist.2015+.x86_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/VCRedist/2015+/x86_Pckgr/14.38.33130.0/Microsoft.VCRedist.2015+.x86_Pckgr.yaml
=> Microsoft.VCRedist.2015+.x86_Pckgr version 14.38.33130.0

manifests/m/Microsoft/VCRedist/2015+/x64_Pckgr/14.38.33130.0/Microsoft.VCRedist.2015+.x64_Pckgr.installer.yaml, manifests/m/Microsoft/VCRedist/2015+/x64_Pckgr/14.38.33130.0/Microsoft.VCRedist.2015+.x64_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/VCRedist/2015+/x64_Pckgr/14.38.33130.0/Microsoft.VCRedist.2015+.x64_Pckgr.yaml
=> Microsoft.VCRedist.2015+.x64_Pckgr version 14.38.33130.0

manifests/p/Postman/Postman_Pckgr/10.23.0/Postman.Postman_Pckgr.installer.yaml, manifests/p/Postman/Postman_Pckgr/10.23.0/Postman.Postman_Pckgr.locale.en-US.yaml, manifests/p/Postman/Postman_Pckgr/10.23.0/Postman.Postman_Pckgr.yaml
=> New version: Postman.Postman_Pckgr version 10.23.0

manifests/e/evernote/evernote_Pckgr/10.75.2/evernote.evernote_Pckgr.installer.yaml, manifests/e/evernote/evernote_Pckgr/10.75.2/evernote.evernote_Pckgr.locale.en-US.yaml, manifests/e/evernote/evernote_Pckgr/10.75.2/evernote.evernote_Pckgr.yaml
=> New version: evernote.evernote_Pckgr version 10.75.2

manifests/a/Amazon/AWSCLI_Pckgr/2.15.19/Amazon.AWSCLI_Pckgr.installer.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.19/Amazon.AWSCLI_Pckgr.locale.en-US.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.19/Amazon.AWSCLI_Pckgr.yaml
=> New version: Amazon.AWSCLI_Pckgr version 2.15.19

manifests/m/Malwarebytes/Malwarebytes_Pckgr/4.6.8.311/Malwarebytes.Malwarebytes_Pckgr.installer.yaml, manifests/m/Malwarebytes/Malwarebytes_Pckgr/4.6.8.311/Malwarebytes.Malwarebytes_Pckgr.locale.en-US.yaml, manifests/m/Malwarebytes/Malwarebytes_Pckgr/4.6.8.311/Malwarebytes.Malwarebytes_Pckgr.yaml
=> New version: Malwarebytes.Malwarebytes_Pckgr version 4.6.8.311

manifests/h/HandBrake/HandBrake_Pckgr/1.7.3/HandBrake.HandBrake_Pckgr.installer.yaml, manifests/h/HandBrake/HandBrake_Pckgr/1.7.3/HandBrake.HandBrake_Pckgr.locale.en-US.yaml, manifests/h/HandBrake/HandBrake_Pckgr/1.7.3/HandBrake.HandBrake_Pckgr.yaml
=> New version: HandBrake.HandBrake_Pckgr version 1.7.3

manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.32.0/Microsoft.Azure.StorageExplorer_Pckgr.installer.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.32.0/Microsoft.Azure.StorageExplorer_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.32.0/Microsoft.Azure.StorageExplorer_Pckgr.yaml
=> New version: Microsoft.Azure.StorageExplorer_Pckgr version 1.32.0

manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.32.1/Microsoft.Azure.StorageExplorer_Pckgr.installer.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.32.1/Microsoft.Azure.StorageExplorer_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.32.1/Microsoft.Azure.StorageExplorer_Pckgr.yaml
=> New version: Microsoft.Azure.StorageExplorer_Pckgr version 1.32.1

manifests/c/Cisco/WebexTeams_Pckgr/44.2.0.28714/Cisco.WebexTeams_Pckgr.installer.yaml, manifests/c/Cisco/WebexTeams_Pckgr/44.2.0.28714/Cisco.WebexTeams_Pckgr.locale.en-US.yaml, manifests/c/Cisco/WebexTeams_Pckgr/44.2.0.28714/Cisco.WebexTeams_Pckgr.yaml
=> New version: Cisco.WebexTeams_Pckgr version 44.2.0.28714

manifests/o/OpenVPNTechnologies/OpenVPNConnect_Pckgr/3.4.4/OpenVPNTechnologies.OpenVPNConnect_Pckgr.installer.yaml, manifests/o/OpenVPNTechnologies/OpenVPNConnect_Pckgr/3.4.4/OpenVPNTechnologies.OpenVPNConnect_Pckgr.locale.en-US.yaml, manifests/o/OpenVPNTechnologies/OpenVPNConnect_Pckgr/3.4.4/OpenVPNTechnologies.OpenVPNConnect_Pckgr.yaml
=> New version: OpenVPNTechnologies.OpenVPNConnect_Pckgr version 3.4.4

manifests/o/OpenVPNTechnologies/OpenVPN_Pckgr/2.6.901/OpenVPNTechnologies.OpenVPN_Pckgr.installer.yaml, manifests/o/OpenVPNTechnologies/OpenVPN_Pckgr/2.6.901/OpenVPNTechnologies.OpenVPN_Pckgr.locale.en-US.yaml, manifests/o/OpenVPNTechnologies/OpenVPN_Pckgr/2.6.901/OpenVPNTechnologies.OpenVPN_Pckgr.yaml
=> New version: OpenVPNTechnologies.OpenVPN_Pckgr version 2.6.901

manifests/o/Opera/Opera_Pckgr/107.0.5045.21/Opera.Opera_Pckgr.installer.yaml, manifests/o/Opera/Opera_Pckgr/107.0.5045.21/Opera.Opera_Pckgr.locale.en-US.yaml, manifests/o/Opera/Opera_Pckgr/107.0.5045.21/Opera.Opera_Pckgr.locale.nb-NO.yaml, manifests/o/Opera/Opera_Pckgr/107.0.5045.21/Opera.Opera_Pckgr.yaml
=> New version: Opera.Opera_Pckgr version 107.0.5045.21

manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/23.008.20533/Adobe.Acrobat.Reader.64-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/23.008.20533/Adobe.Acrobat.Reader.64-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/23.008.20533/Adobe.Acrobat.Reader.64-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.64-bit_Pckgr version 23.008.20533

manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/23.008.20533/Adobe.Acrobat.Reader.32-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/23.008.20533/Adobe.Acrobat.Reader.32-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/23.008.20533/Adobe.Acrobat.Reader.32-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.32-bit_Pckgr version 23.008.20533

manifests/g/Google/Chrome_Pckgr/121.0.6167.184/Google.Chrome_Pckgr.installer.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.184/Google.Chrome_Pckgr.locale.en-US.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.184/Google.Chrome_Pckgr.locale.nb-NO.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.184/Google.Chrome_Pckgr.locale.zh-CN.yaml, manifests/g/Google/Chrome_Pckgr/121.0.6167.184/Google.Chrome_Pckgr.yaml
=> New version: Google.Chrome_Pckgr version 121.0.6167.184

manifests/d/dnGrep/dnGrep_Pckgr/4.1.27.0/dnGrep.dnGrep_Pckgr.installer.yaml, manifests/d/dnGrep/dnGrep_Pckgr/4.1.27.0/dnGrep.dnGrep_Pckgr.locale.en-US.yaml, manifests/d/dnGrep/dnGrep_Pckgr/4.1.27.0/dnGrep.dnGrep_Pckgr.yaml
=> New version: dnGrep.dnGrep_Pckgr version 4.1.27.0

manifests/k/Kitware/CMake_Pckgr/3.29.0-rc1/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.0-rc1/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.0-rc1/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.29.0-rc1

manifests/t/TechSmith/Camtasia_Pckgr/23.4.3.51546/TechSmith.Camtasia_Pckgr.installer.yaml, manifests/t/TechSmith/Camtasia_Pckgr/23.4.3.51546/TechSmith.Camtasia_Pckgr.locale.en-US.yaml, manifests/t/TechSmith/Camtasia_Pckgr/23.4.3.51546/TechSmith.Camtasia_Pckgr.yaml
=> New version: TechSmith.Camtasia_Pckgr version 23.4.3.51546

manifests/t/TimKosse/FileZilla_Pckgr/3.65.0/TimKosse.FileZilla_Pckgr.installer.yaml, manifests/t/TimKosse/FileZilla_Pckgr/3.65.0/TimKosse.FileZilla_Pckgr.locale.en-US.yaml, manifests/t/TimKosse/FileZilla_Pckgr/3.65.0/TimKosse.FileZilla_Pckgr.yaml
=> TimKosse.FileZilla_Pckgr version 3.65.0

manifests/n/Nextcloud/NextcloudDesktop_Pckgr/3.12.0/Nextcloud.NextcloudDesktop_Pckgr.installer.yaml, manifests/n/Nextcloud/NextcloudDesktop_Pckgr/3.12.0/Nextcloud.NextcloudDesktop_Pckgr.locale.en-US.yaml, manifests/n/Nextcloud/NextcloudDesktop_Pckgr/3.12.0/Nextcloud.NextcloudDesktop_Pckgr.yaml
=> New version: Nextcloud.NextcloudDesktop_Pckgr version 3.12.0

manifests/d/Discord/Discord_Pckgr/1.0.9033/Discord.Discord_Pckgr.installer.yaml, manifests/d/Discord/Discord_Pckgr/1.0.9033/Discord.Discord_Pckgr.locale.en-US.yaml, manifests/d/Discord/Discord_Pckgr/1.0.9033/Discord.Discord_Pckgr.locale.pt-BR.yaml, manifests/d/Discord/Discord_Pckgr/1.0.9033/Discord.Discord_Pckgr.locale.zh-CN.yaml, manifests/d/Discord/Discord_Pckgr/1.0.9033/Discord.Discord_Pckgr.yaml
=> New version: Discord.Discord_Pckgr version 1.0.9033

manifests/a/Axosoft/GitKraken_Pckgr/9.12.0/Axosoft.GitKraken_Pckgr.installer.yaml, manifests/a/Axosoft/GitKraken_Pckgr/9.12.0/Axosoft.GitKraken_Pckgr.locale.en-US.yaml, manifests/a/Axosoft/GitKraken_Pckgr/9.12.0/Axosoft.GitKraken_Pckgr.yaml
=> New version: Axosoft.GitKraken_Pckgr version 9.12.0

manifests/v/VMware/WorkstationPlayer_Pckgr/17.0.2/VMware.WorkstationPlayer_Pckgr.installer.yaml, manifests/v/VMware/WorkstationPlayer_Pckgr/17.0.2/VMware.WorkstationPlayer_Pckgr.locale.en-US.yaml, manifests/v/VMware/WorkstationPlayer_Pckgr/17.0.2/VMware.WorkstationPlayer_Pckgr.yaml
=> VMware.WorkstationPlayer_Pckgr version 17.0.2

manifests/v/VMware/WorkstationPro_Pckgr/17.5.0/VMware.WorkstationPro_Pckgr.installer.yaml, manifests/v/VMware/WorkstationPro_Pckgr/17.5.0/VMware.WorkstationPro_Pckgr.locale.en-US.yaml, manifests/v/VMware/WorkstationPro_Pckgr/17.5.0/VMware.WorkstationPro_Pckgr.yaml
=> VMware.WorkstationPro_Pckgr version 17.5.0

manifests/t/TimKosse/FileZilla_Pckgr/3.66.5/TimKosse.FileZilla_Pckgr.installer.yaml, manifests/t/TimKosse/FileZilla_Pckgr/3.66.5/TimKosse.FileZilla_Pckgr.locale.en-US.yaml, manifests/t/TimKosse/FileZilla_Pckgr/3.66.5/TimKosse.FileZilla_Pckgr.yaml
=> New version: TimKosse.FileZilla_Pckgr version 3.66.5

manifests/p/PDFsam/PDFsam_Pckgr/5.2.2/PDFsam.PDFsam_Pckgr.installer.yaml, manifests/p/PDFsam/PDFsam_Pckgr/5.2.2/PDFsam.PDFsam_Pckgr.locale.en-US.yaml, manifests/p/PDFsam/PDFsam_Pckgr/5.2.2/PDFsam.PDFsam_Pckgr.yaml
=> New version: PDFsam.PDFsam_Pckgr version 5.2.2

manifests/a/Amazon/AWSCLI_Pckgr/2.15.20/Amazon.AWSCLI_Pckgr.installer.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.20/Amazon.AWSCLI_Pckgr.locale.en-US.yaml, manifests/a/Amazon/AWSCLI_Pckgr/2.15.20/Amazon.AWSCLI_Pckgr.yaml
=> New version: Amazon.AWSCLI_Pckgr version 2.15.20

manifests/m/Microsoft/Teams/Classic_Pckgr/1.7.00.3653/Microsoft.Teams.Classic_Pckgr.installer.yaml, manifests/m/Microsoft/Teams/Classic_Pckgr/1.7.00.3653/Microsoft.Teams.Classic_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Teams/Classic_Pckgr/1.7.00.3653/Microsoft.Teams.Classic_Pckgr.yaml
=> New version: Microsoft.Teams.Classic_Pckgr version 1.7.00.3653

manifests/g/Google/Chrome_Pckgr/122.0.6261.39/Google.Chrome_Pckgr.installer.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.39/Google.Chrome_Pckgr.locale.en-US.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.39/Google.Chrome_Pckgr.locale.nb-NO.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.39/Google.Chrome_Pckgr.locale.zh-CN.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.39/Google.Chrome_Pckgr.yaml
=> New version: Google.Chrome_Pckgr version 122.0.6261.39

manifests/o/OpenJS/NodeJS_Pckgr/21.6.2/OpenJS.NodeJS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.6.2/OpenJS.NodeJS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.6.2/OpenJS.NodeJS_Pckgr.locale.zh-CN.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.6.2/OpenJS.NodeJS_Pckgr.yaml
=> New version: OpenJS.NodeJS_Pckgr version 21.6.2

manifests/e/evernote/evernote_Pckgr/10.76.2/evernote.evernote_Pckgr.installer.yaml, manifests/e/evernote/evernote_Pckgr/10.76.2/evernote.evernote_Pckgr.locale.en-US.yaml, manifests/e/evernote/evernote_Pckgr/10.76.2/evernote.evernote_Pckgr.yaml
=> New version: evernote.evernote_Pckgr version 10.76.2

manifests/o/OpenWhisperSystems/Signal_Pckgr/6.47.1/OpenWhisperSystems.Signal_Pckgr.installer.yaml, manifests/o/OpenWhisperSystems/Signal_Pckgr/6.47.1/OpenWhisperSystems.Signal_Pckgr.locale.en-US.yaml, manifests/o/OpenWhisperSystems/Signal_Pckgr/6.47.1/OpenWhisperSystems.Signal_Pckgr.yaml
=> New version: OpenWhisperSystems.Signal_Pckgr version 6.47.1

manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.11.1/OpenJS.NodeJS.LTS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.11.1/OpenJS.NodeJS.LTS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.11.1/OpenJS.NodeJS.LTS_Pckgr.yaml
=> New version: OpenJS.NodeJS.LTS_Pckgr version 20.11.1

manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1314/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1314/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1314/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1314/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.64.1314

manifests/m/Microsoft/Skype_Pckgr/8.112.0.210/Microsoft.Skype_Pckgr.installer.yaml, manifests/m/Microsoft/Skype_Pckgr/8.112.0.210/Microsoft.Skype_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Skype_Pckgr/8.112.0.210/Microsoft.Skype_Pckgr.yaml
=> New version: Microsoft.Skype_Pckgr version 8.112.0.210

manifests/w/WiresharkFoundation/Wireshark_Pckgr/4.2.3/WiresharkFoundation.Wireshark_Pckgr.installer.yaml, manifests/w/WiresharkFoundation/Wireshark_Pckgr/4.2.3/WiresharkFoundation.Wireshark_Pckgr.locale.en-US.yaml, manifests/w/WiresharkFoundation/Wireshark_Pckgr/4.2.3/WiresharkFoundation.Wireshark_Pckgr.yaml
=> New version: WiresharkFoundation.Wireshark_Pckgr version 4.2.3

manifests/g/GitHub/cli_Pckgr/2.44.0/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.44.0/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.44.0/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.44.0

manifests/c/CodecGuide/K-LiteCodecPack/Full_Pckgr/18.1.0/CodecGuide.K-LiteCodecPack.Full_Pckgr.installer.yaml, manifests/c/CodecGuide/K-LiteCodecPack/Full_Pckgr/18.1.0/CodecGuide.K-LiteCodecPack.Full_Pckgr.locale.en-US.yaml, manifests/c/CodecGuide/K-LiteCodecPack/Full_Pckgr/18.1.0/CodecGuide.K-LiteCodecPack.Full_Pckgr.yaml
=> New version: CodecGuide.K-LiteCodecPack.Full_Pckgr version 18.1.0

manifests/d/Dialpad/Dialpad_Pckgr/2402.1.0/Dialpad.Dialpad_Pckgr.installer.yaml, manifests/d/Dialpad/Dialpad_Pckgr/2402.1.0/Dialpad.Dialpad_Pckgr.locale.en-US.yaml, manifests/d/Dialpad/Dialpad_Pckgr/2402.1.0/Dialpad.Dialpad_Pckgr.yaml
=> New version: Dialpad.Dialpad_Pckgr version 2402.1.0

manifests/m/Microsoft/Edge_Pckgr/121.0.2277.128/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.128/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.128/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/121.0.2277.128/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 121.0.2277.128

manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1316/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1316/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1316/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1316/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.64.1316

manifests/t/tailscale/tailscale_Pckgr/1.60.0/tailscale.tailscale_Pckgr.installer.yaml, manifests/t/tailscale/tailscale_Pckgr/1.60.0/tailscale.tailscale_Pckgr.locale.en-US.yaml, manifests/t/tailscale/tailscale_Pckgr/1.60.0/tailscale.tailscale_Pckgr.yaml
=> New version: tailscale.tailscale_Pckgr version 1.60.0

manifests/w/WinSCP/WinSCP_Pckgr/6.3/WinSCP.WinSCP_Pckgr.installer.yaml, manifests/w/WinSCP/WinSCP_Pckgr/6.3/WinSCP.WinSCP_Pckgr.locale.en-US.yaml, manifests/w/WinSCP/WinSCP_Pckgr/6.3/WinSCP.WinSCP_Pckgr.yaml
=> New version: WinSCP.WinSCP_Pckgr version 6.3

manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.2/Microsoft.VisualStudioCode_Pckgr.installer.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.2/Microsoft.VisualStudioCode_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.86.2/Microsoft.VisualStudioCode_Pckgr.yaml
=> New version: Microsoft.VisualStudioCode_Pckgr version 1.86.2

manifests/g/GitHub/cli_Pckgr/2.44.1/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.44.1/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.44.1/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.44.1

manifests/j/JGraph/Draw_Pckgr/23.1.5/JGraph.Draw_Pckgr.installer.yaml, manifests/j/JGraph/Draw_Pckgr/23.1.5/JGraph.Draw_Pckgr.locale.en-US.yaml, manifests/j/JGraph/Draw_Pckgr/23.1.5/JGraph.Draw_Pckgr.yaml
=> New version: JGraph.Draw_Pckgr version 23.1.5

manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1318/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1318/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1318/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.64.1318/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.64.1318

manifests/m/Microsoft/PowerBI_Pckgr/2.126.927.0/Microsoft.PowerBI_Pckgr.installer.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.126.927.0/Microsoft.PowerBI_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.126.927.0/Microsoft.PowerBI_Pckgr.yaml
=> New version: Microsoft.PowerBI_Pckgr version 2.126.927.0

manifests/a/Amazon/AWSVPNClient_Pckgr/3.11.1/Amazon.AWSVPNClient_Pckgr.installer.yaml, manifests/a/Amazon/AWSVPNClient_Pckgr/3.11.1/Amazon.AWSVPNClient_Pckgr.locale.en-US.yaml, manifests/a/Amazon/AWSVPNClient_Pckgr/3.11.1/Amazon.AWSVPNClient_Pckgr.yaml
=> New version: Amazon.AWSVPNClient_Pckgr version 3.11.1

manifests/a/Anydo/Anydo_Pckgr/5.0.59.2/Anydo.Anydo_Pckgr.installer.yaml, manifests/a/Anydo/Anydo_Pckgr/5.0.59.2/Anydo.Anydo_Pckgr.locale.en-US.yaml, manifests/a/Anydo/Anydo_Pckgr/5.0.59.2/Anydo.Anydo_Pckgr.yaml
=> New version: Anydo.Anydo_Pckgr version 5.0.59.2

manifests/n/Notepad++/Notepad++_Pckgr/8.6.3/Notepad++.Notepad++_Pckgr.installer.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.3/Notepad++.Notepad++_Pckgr.locale.en-US.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.3/Notepad++.Notepad++_Pckgr.yaml
=> New version: Notepad++.Notepad++_Pckgr version 8.6.3

manifests/d/dbeaver/dbeaver_Pckgr/23.3.5/dbeaver.dbeaver_Pckgr.installer.yaml, manifests/d/dbeaver/dbeaver_Pckgr/23.3.5/dbeaver.dbeaver_Pckgr.locale.en-US.yaml, manifests/d/dbeaver/dbeaver_Pckgr/23.3.5/dbeaver.dbeaver_Pckgr.yaml
=> New version: dbeaver.dbeaver_Pckgr version 23.3.5

manifests/c/Canva/Canva_Pckgr/1.82.0/Canva.Canva_Pckgr.installer.yaml, manifests/c/Canva/Canva_Pckgr/1.82.0/Canva.Canva_Pckgr.locale.en-US.yaml, manifests/c/Canva/Canva_Pckgr/1.82.0/Canva.Canva_Pckgr.yaml
=> New version: Canva.Canva_Pckgr version 1.82.0

manifests/n/Notepad++/Notepad++_Pckgr/8.6.4/Notepad++.Notepad++_Pckgr.installer.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.4/Notepad++.Notepad++_Pckgr.locale.en-US.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.4/Notepad++.Notepad++_Pckgr.yaml
=> New version: Notepad++.Notepad++_Pckgr version 8.6.4

manifests/p/Postman/Postman_Pckgr/10.23.5/Postman.Postman_Pckgr.installer.yaml, manifests/p/Postman/Postman_Pckgr/10.23.5/Postman.Postman_Pckgr.locale.en-US.yaml, manifests/p/Postman/Postman_Pckgr/10.23.5/Postman.Postman_Pckgr.yaml
=> New version: Postman.Postman_Pckgr version 10.23.5

manifests/g/Google/Chrome_Pckgr/122.0.6261.57/Google.Chrome_Pckgr.installer.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.57/Google.Chrome_Pckgr.locale.en-US.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.57/Google.Chrome_Pckgr.locale.nb-NO.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.57/Google.Chrome_Pckgr.locale.zh-CN.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.57/Google.Chrome_Pckgr.yaml
=> New version: Google.Chrome_Pckgr version 122.0.6261.57

manifests/g/Google/Chrome_Pckgr/122.0.6261.58/Google.Chrome_Pckgr.installer.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.58/Google.Chrome_Pckgr.locale.en-US.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.58/Google.Chrome_Pckgr.locale.nb-NO.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.58/Google.Chrome_Pckgr.locale.zh-CN.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.58/Google.Chrome_Pckgr.yaml
=> New version: Google.Chrome_Pckgr version 122.0.6261.58

manifests/a/AgileBits/1Password_Pckgr/8.10.26/AgileBits.1Password_Pckgr.installer.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.26/AgileBits.1Password_Pckgr.locale.en-US.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.26/AgileBits.1Password_Pckgr.yaml
=> New version: AgileBits.1Password_Pckgr version 8.10.26

manifests/m/Microsoft/Bicep_Pckgr/0.25.53/Microsoft.Bicep_Pckgr.installer.yaml, manifests/m/Microsoft/Bicep_Pckgr/0.25.53/Microsoft.Bicep_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Bicep_Pckgr/0.25.53/Microsoft.Bicep_Pckgr.yaml
=> New version: Microsoft.Bicep_Pckgr version 0.25.53

manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.installer.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.en-US.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.fr-FR.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.it-IT.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.ja-JP.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.ko-KR.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.pt-BR.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.ru-RU.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.zh-CN.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.locale.zh-TW.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10302.0/Microsoft.WindowsTerminal.yaml
=> New version: Microsoft.WindowsTerminal version 1.19.10302.0

manifests/e/evernote/evernote_Pckgr/10.77.3/evernote.evernote_Pckgr.installer.yaml, manifests/e/evernote/evernote_Pckgr/10.77.3/evernote.evernote_Pckgr.locale.en-US.yaml, manifests/e/evernote/evernote_Pckgr/10.77.3/evernote.evernote_Pckgr.yaml
=> New version: evernote.evernote_Pckgr version 10.77.3

manifests/k/Kitware/CMake_Pckgr/3.29.0-rc2/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.0-rc2/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.0-rc2/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.29.0-rc2

manifests/g/Grammarly/Grammarly_Pckgr/1.2.65.1324/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.65.1324/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.65.1324/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.65.1324/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.65.1324

manifests/g/GitHub/GitHubDesktop_Pckgr/3.3.9/GitHub.GitHubDesktop_Pckgr.installer.yaml, manifests/g/GitHub/GitHubDesktop_Pckgr/3.3.9/GitHub.GitHubDesktop_Pckgr.locale.en-US.yaml, manifests/g/GitHub/GitHubDesktop_Pckgr/3.3.9/GitHub.GitHubDesktop_Pckgr.yaml
=> New version: GitHub.GitHubDesktop_Pckgr version 3.3.9

manifests/g/Google/Chrome_Pckgr/122.0.6261.70/Google.Chrome_Pckgr.installer.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.70/Google.Chrome_Pckgr.locale.en-US.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.70/Google.Chrome_Pckgr.locale.nb-NO.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.70/Google.Chrome_Pckgr.locale.zh-CN.yaml, manifests/g/Google/Chrome_Pckgr/122.0.6261.70/Google.Chrome_Pckgr.yaml
=> New version: Google.Chrome_Pckgr version 122.0.6261.70

manifests/n/NordSecurity/NordPass_Pckgr/5.13.26/NordSecurity.NordPass_Pckgr.installer.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.13.26/NordSecurity.NordPass_Pckgr.locale.en-US.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.13.26/NordSecurity.NordPass_Pckgr.yaml
=> New version: NordSecurity.NordPass_Pckgr version 5.13.26

manifests/r/RingCentral/RingCentral_Pckgr/24.1.16.9318/RingCentral.RingCentral_Pckgr.installer.yaml, manifests/r/RingCentral/RingCentral_Pckgr/24.1.16.9318/RingCentral.RingCentral_Pckgr.locale.en-US.yaml, manifests/r/RingCentral/RingCentral_Pckgr/24.1.16.9318/RingCentral.RingCentral_Pckgr.yaml
=> New version: RingCentral.RingCentral_Pckgr version 24.1.16.9318

manifests/w/WinSCP/WinSCP_Pckgr/6.3.1/WinSCP.WinSCP_Pckgr.installer.yaml, manifests/w/WinSCP/WinSCP_Pckgr/6.3.1/WinSCP.WinSCP_Pckgr.locale.en-US.yaml, manifests/w/WinSCP/WinSCP_Pckgr/6.3.1/WinSCP.WinSCP_Pckgr.yaml
=> New version: WinSCP.WinSCP_Pckgr version 6.3.1

manifests/m/Microsoft/Edge_Pckgr/122.0.2365.52/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.52/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.52/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.52/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 122.0.2365.52

manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/5.17.10.1010/Zoom.ZoomOutlookPlugin_Pckgr.installer.yaml, manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/5.17.10.1010/Zoom.ZoomOutlookPlugin_Pckgr.locale.en-US.yaml, manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/5.17.10.1010/Zoom.ZoomOutlookPlugin_Pckgr.locale.zh-CN.yaml, manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/5.17.10.1010/Zoom.ZoomOutlookPlugin_Pckgr.yaml
=> New version: Zoom.ZoomOutlookPlugin_Pckgr version 5.17.10.1010

manifests/z/Zoom/Zoom_Pckgr/5.17.10.33775/Zoom.Zoom_Pckgr.installer.yaml, manifests/z/Zoom/Zoom_Pckgr/5.17.10.33775/Zoom.Zoom_Pckgr.locale.en-US.yaml, manifests/z/Zoom/Zoom_Pckgr/5.17.10.33775/Zoom.Zoom_Pckgr.locale.zh-CN.yaml, manifests/z/Zoom/Zoom_Pckgr/5.17.10.33775/Zoom.Zoom_Pckgr.yaml
=> New version: Zoom.Zoom_Pckgr version 5.17.10.33775

manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/23.008.20555/Adobe.Acrobat.Reader.64-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/23.008.20555/Adobe.Acrobat.Reader.64-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/23.008.20555/Adobe.Acrobat.Reader.64-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.64-bit_Pckgr version 23.008.20555

manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/23.008.20555/Adobe.Acrobat.Reader.32-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/23.008.20555/Adobe.Acrobat.Reader.32-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/23.008.20555/Adobe.Acrobat.Reader.32-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.32-bit_Pckgr version 23.008.20555

manifests/d/Docker/DockerDesktop_Pckgr/4.28.0/Docker.DockerDesktop_Pckgr.installer.yaml, manifests/d/Docker/DockerDesktop_Pckgr/4.28.0/Docker.DockerDesktop_Pckgr.locale.en-US.yaml, manifests/d/Docker/DockerDesktop_Pckgr/4.28.0/Docker.DockerDesktop_Pckgr.yaml
=> New version: Docker.DockerDesktop_Pckgr version 4.28.0

manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.5/TeamViewer.TeamViewer_Pckgr.installer.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.5/TeamViewer.TeamViewer_Pckgr.locale.de-DE.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.5/TeamViewer.TeamViewer_Pckgr.locale.en-US.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.5/TeamViewer.TeamViewer_Pckgr.locale.zh-CN.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.5/TeamViewer.TeamViewer_Pckgr.yaml
=> New version: TeamViewer.TeamViewer_Pckgr version 15.51.5

manifests/t/TeamViewer/TeamViewer/Host_Pckgr/15.51.5/TeamViewer.TeamViewer.Host_Pckgr.installer.yaml, manifests/t/TeamViewer/TeamViewer/Host_Pckgr/15.51.5/TeamViewer.TeamViewer.Host_Pckgr.locale.en-US.yaml, manifests/t/TeamViewer/TeamViewer/Host_Pckgr/15.51.5/TeamViewer.TeamViewer.Host_Pckgr.yaml
=> New version: TeamViewer.TeamViewer.Host_Pckgr version 15.51.5

manifests/m/Microsoft/Edge_Pckgr/122.0.2365.59/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.59/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.59/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.59/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 122.0.2365.59

manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.installer.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.en-US.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.fr-FR.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.it-IT.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.ja-JP.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.ko-KR.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.pt-BR.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.ru-RU.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.zh-CN.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.locale.zh-TW.yaml, manifests/m/Microsoft/WindowsTerminal/1.19.10573.0/Microsoft.WindowsTerminal.yaml
=> New version: Microsoft.WindowsTerminal version 1.19.10573.0

manifests/m/Microsoft/AzureCLI_Pckgr/2.57.0/Microsoft.AzureCLI_Pckgr.installer.yaml, manifests/m/Microsoft/AzureCLI_Pckgr/2.57.0/Microsoft.AzureCLI_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/AzureCLI_Pckgr/2.57.0/Microsoft.AzureCLI_Pckgr.yaml
=> New version: Microsoft.AzureCLI_Pckgr version 2.57.0

manifests/e/evernote/evernote_Pckgr/10.78.2/evernote.evernote_Pckgr.installer.yaml, manifests/e/evernote/evernote_Pckgr/10.78.2/evernote.evernote_Pckgr.locale.en-US.yaml, manifests/e/evernote/evernote_Pckgr/10.78.2/evernote.evernote_Pckgr.yaml
=> New version: evernote.evernote_Pckgr version 10.78.2

manifests/m/Microsoft/VisualStudioCode_Pckgr/1.87.0/Microsoft.VisualStudioCode_Pckgr.installer.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.87.0/Microsoft.VisualStudioCode_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/VisualStudioCode_Pckgr/1.87.0/Microsoft.VisualStudioCode_Pckgr.yaml
=> New version: Microsoft.VisualStudioCode_Pckgr version 1.87.0

manifests/m/Microsoft/AzureDataStudio_Pckgr/1.48.0/Microsoft.AzureDataStudio_Pckgr.installer.yaml, manifests/m/Microsoft/AzureDataStudio_Pckgr/1.48.0/Microsoft.AzureDataStudio_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/AzureDataStudio_Pckgr/1.48.0/Microsoft.AzureDataStudio_Pckgr.yaml
=> New version: Microsoft.AzureDataStudio_Pckgr version 1.48.0

manifests/a/Amazon/WorkspacesClient_Pckgr/5.19.0/Amazon.WorkspacesClient_Pckgr.installer.yaml, manifests/a/Amazon/WorkspacesClient_Pckgr/5.19.0/Amazon.WorkspacesClient_Pckgr.locale.en-US.yaml, manifests/a/Amazon/WorkspacesClient_Pckgr/5.19.0/Amazon.WorkspacesClient_Pckgr.yaml
=> New version: Amazon.WorkspacesClient_Pckgr version 5.19.0

manifests/d/dbeaver/dbeaver_Pckgr/24.0.0/dbeaver.dbeaver_Pckgr.installer.yaml, manifests/d/dbeaver/dbeaver_Pckgr/24.0.0/dbeaver.dbeaver_Pckgr.locale.en-US.yaml, manifests/d/dbeaver/dbeaver_Pckgr/24.0.0/dbeaver.dbeaver_Pckgr.yaml
=> New version: dbeaver.dbeaver_Pckgr version 24.0.0

manifests/c/Cisco/WebexTeams_Pckgr/44.2.0.28859/Cisco.WebexTeams_Pckgr.installer.yaml, manifests/c/Cisco/WebexTeams_Pckgr/44.2.0.28859/Cisco.WebexTeams_Pckgr.locale.en-US.yaml, manifests/c/Cisco/WebexTeams_Pckgr/44.2.0.28859/Cisco.WebexTeams_Pckgr.yaml
=> New version: Cisco.WebexTeams_Pckgr version 44.2.0.28859

manifests/m/Microsoft/Edge_Pckgr/122.0.2365.63/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.63/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.63/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.63/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 122.0.2365.63

manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.33.0/Microsoft.Azure.StorageExplorer_Pckgr.installer.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.33.0/Microsoft.Azure.StorageExplorer_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.33.0/Microsoft.Azure.StorageExplorer_Pckgr.yaml
=> New version: Microsoft.Azure.StorageExplorer_Pckgr version 1.33.0

manifests/m/Microsoft/PowerBI_Pckgr/2.126.1261.0/Microsoft.PowerBI_Pckgr.installer.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.126.1261.0/Microsoft.PowerBI_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.126.1261.0/Microsoft.PowerBI_Pckgr.yaml
=> New version: Microsoft.PowerBI_Pckgr version 2.126.1261.0

manifests/a/AgileBits/1Password_Pckgr/8.10.27/AgileBits.1Password_Pckgr.installer.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.27/AgileBits.1Password_Pckgr.locale.en-US.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.27/AgileBits.1Password_Pckgr.yaml
=> New version: AgileBits.1Password_Pckgr version 8.10.27

manifests/c/Canva/Canva_Pckgr/1.83.0/Canva.Canva_Pckgr.installer.yaml, manifests/c/Canva/Canva_Pckgr/1.83.0/Canva.Canva_Pckgr.locale.en-US.yaml, manifests/c/Canva/Canva_Pckgr/1.83.0/Canva.Canva_Pckgr.yaml
=> New version: Canva.Canva_Pckgr version 1.83.0

manifests/m/Microsoft/PowerToys_Pckgr/0.79.0/Microsoft.PowerToys_Pckgr.installer.yaml, manifests/m/Microsoft/PowerToys_Pckgr/0.79.0/Microsoft.PowerToys_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/PowerToys_Pckgr/0.79.0/Microsoft.PowerToys_Pckgr.yaml
=> New version: Microsoft.PowerToys_Pckgr version 0.79.0

manifests/g/GitHub/cli_Pckgr/2.45.0/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.45.0/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.45.0/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.45.0

manifests/l/Logitech/LogiTune_Pckgr/3.5.249.0/Logitech.LogiTune_Pckgr.installer.yaml, manifests/l/Logitech/LogiTune_Pckgr/3.5.249.0/Logitech.LogiTune_Pckgr.locale.en-US.yaml, manifests/l/Logitech/LogiTune_Pckgr/3.5.249.0/Logitech.LogiTune_Pckgr.yaml
=> New version: Logitech.LogiTune_Pckgr version 3.5.249.0

manifests/e/evernote/evernote_Pckgr/10.79.3/evernote.evernote_Pckgr.installer.yaml, manifests/e/evernote/evernote_Pckgr/10.79.3/evernote.evernote_Pckgr.locale.en-US.yaml, manifests/e/evernote/evernote_Pckgr/10.79.3/evernote.evernote_Pckgr.yaml
=> New version: evernote.evernote_Pckgr version 10.79.3

manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.1/Bitwarden.Bitwarden_Pckgr.installer.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.1/Bitwarden.Bitwarden_Pckgr.locale.en-US.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.1/Bitwarden.Bitwarden_Pckgr.locale.pt-BR.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.1/Bitwarden.Bitwarden_Pckgr.locale.zh-CN.yaml, manifests/b/Bitwarden/Bitwarden_Pckgr/2024.2.1/Bitwarden.Bitwarden_Pckgr.yaml
=> New version: Bitwarden.Bitwarden_Pckgr version 2024.2.1

manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.16.2.140/Egnyte.EgnyteDesktopApp_Pckgr.installer.yaml, manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.16.2.140/Egnyte.EgnyteDesktopApp_Pckgr.locale.en-US.yaml, manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.16.2.140/Egnyte.EgnyteDesktopApp_Pckgr.yaml
=> New version: Egnyte.EgnyteDesktopApp_Pckgr version 3.16.2.140

manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.6/TeamViewer.TeamViewer_Pckgr.installer.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.6/TeamViewer.TeamViewer_Pckgr.locale.de-DE.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.6/TeamViewer.TeamViewer_Pckgr.locale.en-US.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.6/TeamViewer.TeamViewer_Pckgr.locale.zh-CN.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.51.6/TeamViewer.TeamViewer_Pckgr.yaml
=> New version: TeamViewer.TeamViewer_Pckgr version 15.51.6

manifests/a/Axosoft/GitKraken_Pckgr/9.13.0/Axosoft.GitKraken_Pckgr.installer.yaml, manifests/a/Axosoft/GitKraken_Pckgr/9.13.0/Axosoft.GitKraken_Pckgr.locale.en-US.yaml, manifests/a/Axosoft/GitKraken_Pckgr/9.13.0/Axosoft.GitKraken_Pckgr.yaml
=> New version: Axosoft.GitKraken_Pckgr version 9.13.0

manifests/p/Postman/Postman_Pckgr/10.23.9/Postman.Postman_Pckgr.installer.yaml, manifests/p/Postman/Postman_Pckgr/10.23.9/Postman.Postman_Pckgr.locale.en-US.yaml, manifests/p/Postman/Postman_Pckgr/10.23.9/Postman.Postman_Pckgr.yaml
=> New version: Postman.Postman_Pckgr version 10.23.9

manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.2.1.6/Cisco.CiscoWebexMeetings_Pckgr.installer.yaml, manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.2.1.6/Cisco.CiscoWebexMeetings_Pckgr.locale.en-US.yaml, manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.2.1.6/Cisco.CiscoWebexMeetings_Pckgr.yaml
=> New version: Cisco.CiscoWebexMeetings_Pckgr version 44.2.1.6

manifests/m/Microsoft/Office_Pckgr/16.0.17328.20162/Microsoft.Office_Pckgr.installer.yaml, manifests/m/Microsoft/Office_Pckgr/16.0.17328.20162/Microsoft.Office_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Office_Pckgr/16.0.17328.20162/Microsoft.Office_Pckgr.yaml
=> New version: Microsoft.Office_Pckgr version 16.0.17328.20162

manifests/t/TechSmith/Snagit/2024_Pckgr/24.1.0/TechSmith.Snagit.2024_Pckgr.installer.yaml, manifests/t/TechSmith/Snagit/2024_Pckgr/24.1.0/TechSmith.Snagit.2024_Pckgr.locale.en-US.yaml, manifests/t/TechSmith/Snagit/2024_Pckgr/24.1.0/TechSmith.Snagit.2024_Pckgr.yaml
=> New version: TechSmith.Snagit.2024_Pckgr version 24.1.0

manifests/o/OpenJS/NodeJS_Pckgr/21.7.0/OpenJS.NodeJS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.0/OpenJS.NodeJS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.0/OpenJS.NodeJS_Pckgr.locale.zh-CN.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.0/OpenJS.NodeJS_Pckgr.yaml
=> New version: OpenJS.NodeJS_Pckgr version 21.7.0

manifests/m/Microsoft/Edge_Pckgr/122.0.2365.80/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.80/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.80/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.80/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 122.0.2365.80

manifests/g/Grammarly/Grammarly_Pckgr/1.2.67.1336/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.67.1336/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.67.1336/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.67.1336/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.67.1336

manifests/p/Postman/Postman_Pckgr/10.24.0/Postman.Postman_Pckgr.installer.yaml, manifests/p/Postman/Postman_Pckgr/10.24.0/Postman.Postman_Pckgr.locale.en-US.yaml, manifests/p/Postman/Postman_Pckgr/10.24.0/Postman.Postman_Pckgr.yaml
=> New version: Postman.Postman_Pckgr version 10.24.0

manifests/o/OpenJS/NodeJS_Pckgr/21.7.1/OpenJS.NodeJS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.1/OpenJS.NodeJS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.1/OpenJS.NodeJS_Pckgr.locale.zh-CN.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.1/OpenJS.NodeJS_Pckgr.yaml
=> New version: OpenJS.NodeJS_Pckgr version 21.7.1

manifests/z/Zoom/Zoom_Pckgr/5.17.11.34827/Zoom.Zoom_Pckgr.installer.yaml, manifests/z/Zoom/Zoom_Pckgr/5.17.11.34827/Zoom.Zoom_Pckgr.locale.en-US.yaml, manifests/z/Zoom/Zoom_Pckgr/5.17.11.34827/Zoom.Zoom_Pckgr.locale.zh-CN.yaml, manifests/z/Zoom/Zoom_Pckgr/5.17.11.34827/Zoom.Zoom_Pckgr.yaml
=> New version: Zoom.Zoom_Pckgr version 5.17.11.34827

manifests/t/TechSmith/Snagit/2024_Pckgr/24.1.1/TechSmith.Snagit.2024_Pckgr.installer.yaml, manifests/t/TechSmith/Snagit/2024_Pckgr/24.1.1/TechSmith.Snagit.2024_Pckgr.locale.en-US.yaml, manifests/t/TechSmith/Snagit/2024_Pckgr/24.1.1/TechSmith.Snagit.2024_Pckgr.yaml
=> New version: TechSmith.Snagit.2024_Pckgr version 24.1.1

manifests/g/Grammarly/Grammarly_Pckgr/1.2.68.1342/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.68.1342/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.68.1342/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.68.1342/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.68.1342

manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.001.20604/Adobe.Acrobat.Reader.32-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.001.20604/Adobe.Acrobat.Reader.32-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.001.20604/Adobe.Acrobat.Reader.32-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.32-bit_Pckgr version 24.001.20604

manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.001.20604/Adobe.Acrobat.Reader.64-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.001.20604/Adobe.Acrobat.Reader.64-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.001.20604/Adobe.Acrobat.Reader.64-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.64-bit_Pckgr version 24.001.20604

manifests/p/Postman/Postman_Pckgr/10.24.3/Postman.Postman_Pckgr.installer.yaml, manifests/p/Postman/Postman_Pckgr/10.24.3/Postman.Postman_Pckgr.locale.en-US.yaml, manifests/p/Postman/Postman_Pckgr/10.24.3/Postman.Postman_Pckgr.yaml
=> New version: Postman.Postman_Pckgr version 10.24.3

manifests/m/Microsoft/Edge_Pckgr/122.0.2365.92/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.92/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.92/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.92/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 122.0.2365.92

manifests/s/SlackTechnologies/Slack_Pckgr/4.37.94/SlackTechnologies.Slack_Pckgr.installer.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.37.94/SlackTechnologies.Slack_Pckgr.locale.en-US.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.37.94/SlackTechnologies.Slack_Pckgr.yaml
=> New version: SlackTechnologies.Slack_Pckgr version 4.37.94

manifests/k/Kitware/CMake_Pckgr/3.28.4/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.28.4/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.28.4/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.28.4

manifests/g/GitHub/cli_Pckgr/2.46.0/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.46.0/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.46.0/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.46.0

manifests/a/AgileBits/1Password_Pckgr/8.10.28/AgileBits.1Password_Pckgr.installer.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.28/AgileBits.1Password_Pckgr.locale.en-US.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.28/AgileBits.1Password_Pckgr.yaml
=> New version: AgileBits.1Password_Pckgr version 8.10.28

manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.001.20615/Adobe.Acrobat.Reader.64-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.001.20615/Adobe.Acrobat.Reader.64-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.001.20615/Adobe.Acrobat.Reader.64-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.64-bit_Pckgr version 24.001.20615

manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.001.20615/Adobe.Acrobat.Reader.32-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.001.20615/Adobe.Acrobat.Reader.32-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.001.20615/Adobe.Acrobat.Reader.32-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.32-bit_Pckgr version 24.001.20615

manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.3.0.146/Cisco.CiscoWebexMeetings_Pckgr.installer.yaml, manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.3.0.146/Cisco.CiscoWebexMeetings_Pckgr.locale.en-US.yaml, manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.3.0.146/Cisco.CiscoWebexMeetings_Pckgr.yaml
=> New version: Cisco.CiscoWebexMeetings_Pckgr version 44.3.0.146

manifests/k/Kitware/CMake_Pckgr/3.29.0/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.0/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.0/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.29.0

manifests/m/Microsoft/Edge_Pckgr/122.0.2365.106/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.106/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.106/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/122.0.2365.106/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 122.0.2365.106

manifests/s/SlackTechnologies/Slack_Pckgr/4.37.98/SlackTechnologies.Slack_Pckgr.installer.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.37.98/SlackTechnologies.Slack_Pckgr.locale.en-US.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.37.98/SlackTechnologies.Slack_Pckgr.yaml
=> New version: SlackTechnologies.Slack_Pckgr version 4.37.98

manifests/j/JGraph/Draw_Pckgr/24.1.0/JGraph.Draw_Pckgr.installer.yaml, manifests/j/JGraph/Draw_Pckgr/24.1.0/JGraph.Draw_Pckgr.locale.en-US.yaml, manifests/j/JGraph/Draw_Pckgr/24.1.0/JGraph.Draw_Pckgr.yaml
=> New version: JGraph.Draw_Pckgr version 24.1.0

manifests/d/dbeaver/dbeaver_Pckgr/24.0.1/dbeaver.dbeaver_Pckgr.installer.yaml, manifests/d/dbeaver/dbeaver_Pckgr/24.0.1/dbeaver.dbeaver_Pckgr.locale.en-US.yaml, manifests/d/dbeaver/dbeaver_Pckgr/24.0.1/dbeaver.dbeaver_Pckgr.yaml
=> New version: dbeaver.dbeaver_Pckgr version 24.0.1

manifests/n/NordSecurity/NordPass_Pckgr/5.14.23/NordSecurity.NordPass_Pckgr.installer.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.14.23/NordSecurity.NordPass_Pckgr.locale.en-US.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.14.23/NordSecurity.NordPass_Pckgr.yaml
=> New version: NordSecurity.NordPass_Pckgr version 5.14.23

manifests/m/Microsoft/PowerBI_Pckgr/2.127.1080.0/Microsoft.PowerBI_Pckgr.installer.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.127.1080.0/Microsoft.PowerBI_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.127.1080.0/Microsoft.PowerBI_Pckgr.yaml
=> New version: Microsoft.PowerBI_Pckgr version 2.127.1080.0

manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.3/TeamViewer.TeamViewer_Pckgr.installer.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.3/TeamViewer.TeamViewer_Pckgr.locale.de-DE.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.3/TeamViewer.TeamViewer_Pckgr.locale.en-US.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.3/TeamViewer.TeamViewer_Pckgr.locale.zh-CN.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.3/TeamViewer.TeamViewer_Pckgr.yaml
=> New version: TeamViewer.TeamViewer_Pckgr version 15.52.3

manifests/m/Microsoft/Edge_Pckgr/123.0.2420.65/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/123.0.2420.65/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/123.0.2420.65/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/123.0.2420.65/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 123.0.2420.65

manifests/w/WiresharkFoundation/Wireshark_Pckgr/4.2.4/WiresharkFoundation.Wireshark_Pckgr.installer.yaml, manifests/w/WiresharkFoundation/Wireshark_Pckgr/4.2.4/WiresharkFoundation.Wireshark_Pckgr.locale.en-US.yaml, manifests/w/WiresharkFoundation/Wireshark_Pckgr/4.2.4/WiresharkFoundation.Wireshark_Pckgr.yaml
=> New version: WiresharkFoundation.Wireshark_Pckgr version 4.2.4

manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/6.0.0.1012/Zoom.ZoomOutlookPlugin_Pckgr.installer.yaml, manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/6.0.0.1012/Zoom.ZoomOutlookPlugin_Pckgr.locale.en-US.yaml, manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/6.0.0.1012/Zoom.ZoomOutlookPlugin_Pckgr.locale.zh-CN.yaml, manifests/z/Zoom/ZoomOutlookPlugin_Pckgr/6.0.0.1012/Zoom.ZoomOutlookPlugin_Pckgr.yaml
=> New version: Zoom.ZoomOutlookPlugin_Pckgr version 6.0.0.1012

manifests/m/Microsoft/PowerBI_Pckgr/2.127.1235.0/Microsoft.PowerBI_Pckgr.installer.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.127.1235.0/Microsoft.PowerBI_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.127.1235.0/Microsoft.PowerBI_Pckgr.yaml
=> New version: Microsoft.PowerBI_Pckgr version 2.127.1235.0

manifests/m/Microsoft/Teams/Classic_Pckgr/1.7.00.7956/Microsoft.Teams.Classic_Pckgr.installer.yaml, manifests/m/Microsoft/Teams/Classic_Pckgr/1.7.00.7956/Microsoft.Teams.Classic_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Teams/Classic_Pckgr/1.7.00.7956/Microsoft.Teams.Classic_Pckgr.yaml
=> New version: Microsoft.Teams.Classic_Pckgr version 1.7.00.7956

manifests/r/RingCentral/RingCentral_Pckgr/24.1.32.9774/RingCentral.RingCentral_Pckgr.installer.yaml, manifests/r/RingCentral/RingCentral_Pckgr/24.1.32.9774/RingCentral.RingCentral_Pckgr.locale.en-US.yaml, manifests/r/RingCentral/RingCentral_Pckgr/24.1.32.9774/RingCentral.RingCentral_Pckgr.yaml
=> New version: RingCentral.RingCentral_Pckgr version 24.1.32.9774

manifests/o/OpenJS/NodeJS_Pckgr/21.7.2/OpenJS.NodeJS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.2/OpenJS.NodeJS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.2/OpenJS.NodeJS_Pckgr.locale.zh-CN.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.2/OpenJS.NodeJS_Pckgr.yaml
=> New version: OpenJS.NodeJS_Pckgr version 21.7.2

manifests/g/GitHub/cli_Pckgr/2.47.0/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.47.0/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.47.0/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.47.0

manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.4/TeamViewer.TeamViewer_Pckgr.installer.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.4/TeamViewer.TeamViewer_Pckgr.locale.de-DE.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.4/TeamViewer.TeamViewer_Pckgr.locale.en-US.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.4/TeamViewer.TeamViewer_Pckgr.locale.zh-CN.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.52.4/TeamViewer.TeamViewer_Pckgr.yaml
=> New version: TeamViewer.TeamViewer_Pckgr version 15.52.4

manifests/l/Logitech/Sync_Pckgr/3.3.176.0/Logitech.Sync_Pckgr.installer.yaml, manifests/l/Logitech/Sync_Pckgr/3.3.176.0/Logitech.Sync_Pckgr.locale.en-US.yaml, manifests/l/Logitech/Sync_Pckgr/3.3.176.0/Logitech.Sync_Pckgr.yaml
=> New version: Logitech.Sync_Pckgr version 3.3.176.0

manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.12.1/OpenJS.NodeJS.LTS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.12.1/OpenJS.NodeJS.LTS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.12.1/OpenJS.NodeJS.LTS_Pckgr.yaml
=> New version: OpenJS.NodeJS.LTS_Pckgr version 20.12.1

manifests/k/Kitware/CMake_Pckgr/3.29.1/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.1/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.1/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.29.1

manifests/p/Postman/Postman_Pckgr/10.24.16/Postman.Postman_Pckgr.installer.yaml, manifests/p/Postman/Postman_Pckgr/10.24.16/Postman.Postman_Pckgr.locale.en-US.yaml, manifests/p/Postman/Postman_Pckgr/10.24.16/Postman.Postman_Pckgr.yaml
=> New version: Postman.Postman_Pckgr version 10.24.16

manifests/p/Postman/Postman_Pckgr/11.0.0/Postman.Postman_Pckgr.installer.yaml, manifests/p/Postman/Postman_Pckgr/11.0.0/Postman.Postman_Pckgr.locale.en-US.yaml, manifests/p/Postman/Postman_Pckgr/11.0.0/Postman.Postman_Pckgr.yaml
=> New version: Postman.Postman_Pckgr version 11.0.0

manifests/d/dbeaver/dbeaver_Pckgr/24.0.2/dbeaver.dbeaver_Pckgr.installer.yaml, manifests/d/dbeaver/dbeaver_Pckgr/24.0.2/dbeaver.dbeaver_Pckgr.locale.en-US.yaml, manifests/d/dbeaver/dbeaver_Pckgr/24.0.2/dbeaver.dbeaver_Pckgr.yaml
=> New version: dbeaver.dbeaver_Pckgr version 24.0.2

manifests/s/SlackTechnologies/Slack_Pckgr/4.37.101/SlackTechnologies.Slack_Pckgr.installer.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.37.101/SlackTechnologies.Slack_Pckgr.locale.en-US.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.37.101/SlackTechnologies.Slack_Pckgr.yaml
=> New version: SlackTechnologies.Slack_Pckgr version 4.37.101

manifests/d/Docker/DockerDesktop_Pckgr/4.29.0/Docker.DockerDesktop_Pckgr.installer.yaml, manifests/d/Docker/DockerDesktop_Pckgr/4.29.0/Docker.DockerDesktop_Pckgr.locale.en-US.yaml, manifests/d/Docker/DockerDesktop_Pckgr/4.29.0/Docker.DockerDesktop_Pckgr.yaml
=> New version: Docker.DockerDesktop_Pckgr version 4.29.0

manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.4.0.159/Cisco.CiscoWebexMeetings_Pckgr.installer.yaml, manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.4.0.159/Cisco.CiscoWebexMeetings_Pckgr.locale.en-US.yaml, manifests/c/Cisco/CiscoWebexMeetings_Pckgr/44.4.0.159/Cisco.CiscoWebexMeetings_Pckgr.yaml
=> New version: Cisco.CiscoWebexMeetings_Pckgr version 44.4.0.159

manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.12.2/OpenJS.NodeJS.LTS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.12.2/OpenJS.NodeJS.LTS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.12.2/OpenJS.NodeJS.LTS_Pckgr.yaml
=> New version: OpenJS.NodeJS.LTS_Pckgr version 20.12.2

manifests/o/OpenJS/NodeJS_Pckgr/21.7.3/OpenJS.NodeJS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.3/OpenJS.NodeJS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.3/OpenJS.NodeJS_Pckgr.locale.zh-CN.yaml, manifests/o/OpenJS/NodeJS_Pckgr/21.7.3/OpenJS.NodeJS_Pckgr.yaml
=> New version: OpenJS.NodeJS_Pckgr version 21.7.3

manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.33.1/Microsoft.Azure.StorageExplorer_Pckgr.installer.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.33.1/Microsoft.Azure.StorageExplorer_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Azure/StorageExplorer_Pckgr/1.33.1/Microsoft.Azure.StorageExplorer_Pckgr.yaml
=> New version: Microsoft.Azure.StorageExplorer_Pckgr version 1.33.1

manifests/a/Amazon/AWSVPNClient_Pckgr/3.11.2/Amazon.AWSVPNClient_Pckgr.installer.yaml, manifests/a/Amazon/AWSVPNClient_Pckgr/3.11.2/Amazon.AWSVPNClient_Pckgr.locale.en-US.yaml, manifests/a/Amazon/AWSVPNClient_Pckgr/3.11.2/Amazon.AWSVPNClient_Pckgr.yaml
=> New version: Amazon.AWSVPNClient_Pckgr version 3.11.2

manifests/k/Kitware/CMake_Pckgr/3.29.2/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.2/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.2/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.29.2

manifests/r/RingCentral/RingCentral_Pckgr/24.1.33.9929/RingCentral.RingCentral_Pckgr.installer.yaml, manifests/r/RingCentral/RingCentral_Pckgr/24.1.33.9929/RingCentral.RingCentral_Pckgr.locale.en-US.yaml, manifests/r/RingCentral/RingCentral_Pckgr/24.1.33.9929/RingCentral.RingCentral_Pckgr.yaml
=> New version: RingCentral.RingCentral_Pckgr version 24.1.33.9929

manifests/c/Canva/Canva_Pckgr/1.85.0/Canva.Canva_Pckgr.installer.yaml, manifests/c/Canva/Canva_Pckgr/1.85.0/Canva.Canva_Pckgr.locale.en-US.yaml, manifests/c/Canva/Canva_Pckgr/1.85.0/Canva.Canva_Pckgr.yaml
=> New version: Canva.Canva_Pckgr version 1.85.0

manifests/g/Grammarly/Grammarly_Pckgr/1.2.72.1368/Grammarly.Grammarly_Pckgr.installer.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.72.1368/Grammarly.Grammarly_Pckgr.locale.en-US.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.72.1368/Grammarly.Grammarly_Pckgr.locale.zh-CN.yaml, manifests/g/Grammarly/Grammarly_Pckgr/1.2.72.1368/Grammarly.Grammarly_Pckgr.yaml
=> New version: Grammarly.Grammarly_Pckgr version 1.2.72.1368

manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.002.20687/Adobe.Acrobat.Reader.64-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.002.20687/Adobe.Acrobat.Reader.64-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/64-bit_Pckgr/24.002.20687/Adobe.Acrobat.Reader.64-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.64-bit_Pckgr version 24.002.20687

manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.002.20687/Adobe.Acrobat.Reader.32-bit_Pckgr.installer.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.002.20687/Adobe.Acrobat.Reader.32-bit_Pckgr.locale.en-US.yaml, manifests/a/Adobe/Acrobat/Reader/32-bit_Pckgr/24.002.20687/Adobe.Acrobat.Reader.32-bit_Pckgr.yaml
=> New version: Adobe.Acrobat.Reader.32-bit_Pckgr version 24.002.20687

manifests/m/Microsoft/Office_Pckgr/16.0.17531.20046/Microsoft.Office_Pckgr.installer.yaml, manifests/m/Microsoft/Office_Pckgr/16.0.17531.20046/Microsoft.Office_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Office_Pckgr/16.0.17531.20046/Microsoft.Office_Pckgr.yaml
=> New version: Microsoft.Office_Pckgr version 16.0.17531.20046

manifests/j/Jabra/Direct_Pckgr/6.14.08801/Jabra.Direct_Pckgr.installer.yaml, manifests/j/Jabra/Direct_Pckgr/6.14.08801/Jabra.Direct_Pckgr.locale.en-US.yaml, manifests/j/Jabra/Direct_Pckgr/6.14.08801/Jabra.Direct_Pckgr.yaml
=> New version: Jabra.Direct_Pckgr version 6.14.08801

manifests/p/PuTTY/PuTTY_Pckgr/0.81/PuTTY.PuTTY_Pckgr.installer.yaml, manifests/p/PuTTY/PuTTY_Pckgr/0.81/PuTTY.PuTTY_Pckgr.locale.en-US.yaml, manifests/p/PuTTY/PuTTY_Pckgr/0.81/PuTTY.PuTTY_Pckgr.yaml
=> New version: PuTTY.PuTTY_Pckgr version 0.81

manifests/z/Zoom/Zoom_Pckgr/6.0.0.37205/Zoom.Zoom_Pckgr.installer.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.0.37205/Zoom.Zoom_Pckgr.locale.en-US.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.0.37205/Zoom.Zoom_Pckgr.locale.zh-CN.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.0.37205/Zoom.Zoom_Pckgr.yaml
=> New version: Zoom.Zoom_Pckgr version 6.0.0.37205

manifests/b/BlenderFoundation/Blender_Pckgr/4.1.1/BlenderFoundation.Blender_Pckgr.installer.yaml, manifests/b/BlenderFoundation/Blender_Pckgr/4.1.1/BlenderFoundation.Blender_Pckgr.locale.en-US.yaml, manifests/b/BlenderFoundation/Blender_Pckgr/4.1.1/BlenderFoundation.Blender_Pckgr.yaml
=> New version: BlenderFoundation.Blender_Pckgr version 4.1.1

manifests/a/AgileBits/1Password_Pckgr/8.10.30/AgileBits.1Password_Pckgr.installer.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.30/AgileBits.1Password_Pckgr.locale.en-US.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.30/AgileBits.1Password_Pckgr.yaml
=> New version: AgileBits.1Password_Pckgr version 8.10.30

manifests/g/GitHub/cli_Pckgr/2.48.0/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.48.0/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.48.0/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.48.0

manifests/m/Microsoft/Edge_Pckgr/124.0.2478.51/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.51/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.51/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.51/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 124.0.2478.51

manifests/z/Zoom/Zoom_Pckgr/6.0.3.37634/Zoom.Zoom_Pckgr.installer.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.3.37634/Zoom.Zoom_Pckgr.locale.en-US.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.3.37634/Zoom.Zoom_Pckgr.locale.zh-CN.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.3.37634/Zoom.Zoom_Pckgr.yaml
=> New version: Zoom.Zoom_Pckgr version 6.0.3.37634

manifests/n/NordSecurity/NordPass_Pckgr/5.15.27/NordSecurity.NordPass_Pckgr.installer.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.15.27/NordSecurity.NordPass_Pckgr.locale.en-US.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.15.27/NordSecurity.NordPass_Pckgr.yaml
=> New version: NordSecurity.NordPass_Pckgr version 5.15.27

manifests/s/SlackTechnologies/Slack_Pckgr/4.38.115/SlackTechnologies.Slack_Pckgr.installer.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.38.115/SlackTechnologies.Slack_Pckgr.locale.en-US.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.38.115/SlackTechnologies.Slack_Pckgr.yaml
=> New version: SlackTechnologies.Slack_Pckgr version 4.38.115

manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.6/TeamViewer.TeamViewer_Pckgr.installer.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.6/TeamViewer.TeamViewer_Pckgr.locale.de-DE.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.6/TeamViewer.TeamViewer_Pckgr.locale.en-US.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.6/TeamViewer.TeamViewer_Pckgr.locale.zh-CN.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.6/TeamViewer.TeamViewer_Pckgr.yaml
=> New version: TeamViewer.TeamViewer_Pckgr version 15.53.6

manifests/m/Microsoft/PowerBI_Pckgr/2.128.1177.0/Microsoft.PowerBI_Pckgr.installer.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.128.1177.0/Microsoft.PowerBI_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/PowerBI_Pckgr/2.128.1177.0/Microsoft.PowerBI_Pckgr.yaml
=> New version: Microsoft.PowerBI_Pckgr version 2.128.1177.0

manifests/n/NordSecurity/NordPass_Pckgr/5.15.28/NordSecurity.NordPass_Pckgr.installer.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.15.28/NordSecurity.NordPass_Pckgr.locale.en-US.yaml, manifests/n/NordSecurity/NordPass_Pckgr/5.15.28/NordSecurity.NordPass_Pckgr.yaml
=> New version: NordSecurity.NordPass_Pckgr version 5.15.28

manifests/o/OpenJS/NodeJS_Pckgr/22.0.0/OpenJS.NodeJS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS_Pckgr/22.0.0/OpenJS.NodeJS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS_Pckgr/22.0.0/OpenJS.NodeJS_Pckgr.locale.zh-CN.yaml, manifests/o/OpenJS/NodeJS_Pckgr/22.0.0/OpenJS.NodeJS_Pckgr.yaml
=> New version: OpenJS.NodeJS_Pckgr version 22.0.0

manifests/a/AnyDeskSoftwareGmbH/AnyDesk_Pckgr/8.0.10/AnyDeskSoftwareGmbH.AnyDesk_Pckgr.installer.yaml, manifests/a/AnyDeskSoftwareGmbH/AnyDesk_Pckgr/8.0.10/AnyDeskSoftwareGmbH.AnyDesk_Pckgr.locale.en-US.yaml, manifests/a/AnyDeskSoftwareGmbH/AnyDesk_Pckgr/8.0.10/AnyDeskSoftwareGmbH.AnyDesk_Pckgr.locale.zh-CN.yaml, manifests/a/AnyDeskSoftwareGmbH/AnyDesk_Pckgr/8.0.10/AnyDeskSoftwareGmbH.AnyDesk_Pckgr.yaml
=> New version: AnyDeskSoftwareGmbH.AnyDesk_Pckgr version 8.0.10

manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.17.0.143/Egnyte.EgnyteDesktopApp_Pckgr.installer.yaml, manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.17.0.143/Egnyte.EgnyteDesktopApp_Pckgr.locale.en-US.yaml, manifests/e/Egnyte/EgnyteDesktopApp_Pckgr/3.17.0.143/Egnyte.EgnyteDesktopApp_Pckgr.yaml
=> New version: Egnyte.EgnyteDesktopApp_Pckgr version 3.17.0.143

manifests/w/WinMerge/WinMerge_Pckgr/2.16.40/WinMerge.WinMerge_Pckgr.installer.yaml, manifests/w/WinMerge/WinMerge_Pckgr/2.16.40/WinMerge.WinMerge_Pckgr.locale.en-US.yaml, manifests/w/WinMerge/WinMerge_Pckgr/2.16.40/WinMerge.WinMerge_Pckgr.yaml
=> New version: WinMerge.WinMerge_Pckgr version 2.16.40

manifests/z/Zoom/Zoom_Pckgr/6.0.4.38135/Zoom.Zoom_Pckgr.installer.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.4.38135/Zoom.Zoom_Pckgr.locale.en-US.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.4.38135/Zoom.Zoom_Pckgr.locale.zh-CN.yaml, manifests/z/Zoom/Zoom_Pckgr/6.0.4.38135/Zoom.Zoom_Pckgr.yaml
=> New version: Zoom.Zoom_Pckgr version 6.0.4.38135

manifests/a/Amazon/WorkspacesClient_Pckgr/5.19.3/Amazon.WorkspacesClient_Pckgr.installer.yaml, manifests/a/Amazon/WorkspacesClient_Pckgr/5.19.3/Amazon.WorkspacesClient_Pckgr.locale.en-US.yaml, manifests/a/Amazon/WorkspacesClient_Pckgr/5.19.3/Amazon.WorkspacesClient_Pckgr.yaml
=> New version: Amazon.WorkspacesClient_Pckgr version 5.19.3

manifests/k/Kitware/CMake_Pckgr/3.29.3/Kitware.CMake_Pckgr.installer.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.3/Kitware.CMake_Pckgr.locale.en-US.yaml, manifests/k/Kitware/CMake_Pckgr/3.29.3/Kitware.CMake_Pckgr.yaml
=> New version: Kitware.CMake_Pckgr version 3.29.3

manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.7/TeamViewer.TeamViewer_Pckgr.installer.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.7/TeamViewer.TeamViewer_Pckgr.locale.de-DE.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.7/TeamViewer.TeamViewer_Pckgr.locale.en-US.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.7/TeamViewer.TeamViewer_Pckgr.locale.zh-CN.yaml, manifests/t/TeamViewer/TeamViewer_Pckgr/15.53.7/TeamViewer.TeamViewer_Pckgr.yaml
=> New version: TeamViewer.TeamViewer_Pckgr version 15.53.7

manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.13.0/OpenJS.NodeJS.LTS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.13.0/OpenJS.NodeJS.LTS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.13.0/OpenJS.NodeJS.LTS_Pckgr.yaml
=> New version: OpenJS.NodeJS.LTS_Pckgr version 20.13.0

manifests/o/OpenJS/NodeJS_Pckgr/22.1.0/OpenJS.NodeJS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS_Pckgr/22.1.0/OpenJS.NodeJS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS_Pckgr/22.1.0/OpenJS.NodeJS_Pckgr.locale.zh-CN.yaml, manifests/o/OpenJS/NodeJS_Pckgr/22.1.0/OpenJS.NodeJS_Pckgr.yaml
=> New version: OpenJS.NodeJS_Pckgr version 22.1.0

manifests/g/GIMP/GIMP_Pckgr/2.10.38/GIMP.GIMP_Pckgr.installer.yaml, manifests/g/GIMP/GIMP_Pckgr/2.10.38/GIMP.GIMP_Pckgr.locale.en-US.yaml, manifests/g/GIMP/GIMP_Pckgr/2.10.38/GIMP.GIMP_Pckgr.yaml
=> New version: GIMP.GIMP_Pckgr version 2.10.38

manifests/c/Canva/Canva_Pckgr/1.86.1/Canva.Canva_Pckgr.installer.yaml, manifests/c/Canva/Canva_Pckgr/1.86.1/Canva.Canva_Pckgr.locale.en-US.yaml, manifests/c/Canva/Canva_Pckgr/1.86.1/Canva.Canva_Pckgr.yaml
=> New version: Canva.Canva_Pckgr version 1.86.1

manifests/g/GitHub/cli_Pckgr/2.49.1/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.49.1/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.49.1/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.49.1

manifests/m/Microsoft/Edge_Pckgr/124.0.2478.80/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.80/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.80/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.80/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 124.0.2478.80

manifests/s/SlackTechnologies/Slack_Pckgr/4.38.121/SlackTechnologies.Slack_Pckgr.installer.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.38.121/SlackTechnologies.Slack_Pckgr.locale.en-US.yaml, manifests/s/SlackTechnologies/Slack_Pckgr/4.38.121/SlackTechnologies.Slack_Pckgr.yaml
=> New version: SlackTechnologies.Slack_Pckgr version 4.38.121

manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.13.1/OpenJS.NodeJS.LTS_Pckgr.installer.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.13.1/OpenJS.NodeJS.LTS_Pckgr.locale.en-US.yaml, manifests/o/OpenJS/NodeJS/LTS_Pckgr/20.13.1/OpenJS.NodeJS.LTS_Pckgr.yaml
=> New version: OpenJS.NodeJS.LTS_Pckgr version 20.13.1

manifests/m/Microsoft/Edge_Pckgr/124.0.2478.97/Microsoft.Edge_Pckgr.installer.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.97/Microsoft.Edge_Pckgr.locale.en-US.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.97/Microsoft.Edge_Pckgr.locale.nb-NO.yaml, manifests/m/Microsoft/Edge_Pckgr/124.0.2478.97/Microsoft.Edge_Pckgr.yaml
=> New version: Microsoft.Edge_Pckgr version 124.0.2478.97

manifests/n/Notepad++/Notepad++_Pckgr/8.6.7/Notepad++.Notepad++_Pckgr.installer.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.7/Notepad++.Notepad++_Pckgr.locale.en-US.yaml, manifests/n/Notepad++/Notepad++_Pckgr/8.6.7/Notepad++.Notepad++_Pckgr.yaml
=> New version: Notepad++.Notepad++_Pckgr version 8.6.7

manifests/g/GitHub/cli_Pckgr/2.49.2/GitHub.cli_Pckgr.installer.yaml, manifests/g/GitHub/cli_Pckgr/2.49.2/GitHub.cli_Pckgr.locale.en-US.yaml, manifests/g/GitHub/cli_Pckgr/2.49.2/GitHub.cli_Pckgr.yaml
=> New version: GitHub.cli_Pckgr version 2.49.2

manifests/a/AgileBits/1Password_Pckgr/8.10.32/AgileBits.1Password_Pckgr.installer.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.32/AgileBits.1Password_Pckgr.locale.en-US.yaml, manifests/a/AgileBits/1Password_Pckgr/8.10.32/AgileBits.1Password_Pckgr.yaml
=> New version: AgileBits.1Password_Pckgr version 8.10.32
